// swift-tools-version: 6.0
import PackageDescription

/// The renderer-free core of Virtualstudio, as Swift.
///
/// These targets hold the photographic and anatomical arithmetic the web studio
/// already has, and nothing else: no RealityKit, no Metal, no SwiftUI. The
/// dependency direction is the one the TypeScript side already enforces — the
/// pure logic knows nothing about what draws it. An app target may depend on
/// these; they may never depend on an app target.
///
/// Every target is checked against golden fixtures generated by the TypeScript
/// implementation, so a divergence is a test failure in one language rather
/// than a discrepancy nobody notices.
let package = Package(
    name: "VirtualstudioCore",
    platforms: [.iOS(.v17), .macOS(.v14)],
    products: [
        .library(name: "Photometry", targets: ["Photometry"]),
        .library(name: "SceneDocument", targets: ["SceneDocument"]),
        .library(name: "PoseRig", targets: ["PoseRig"]),
        .library(name: "LimbIK", targets: ["LimbIK"]),
        .library(name: "StudioContent", targets: ["StudioContent"]),
        .library(name: "Storyboard", targets: ["Storyboard"]),
    ],
    targets: [
        .target(name: "Photometry"),
        .testTarget(
            name: "PhotometryTests",
            dependencies: ["Photometry"],
            resources: [.copy("Fixtures")]
        ),
        .target(name: "PoseRig"),
        .testTarget(
            name: "PoseRigTests",
            dependencies: ["PoseRig"],
            resources: [.copy("Fixtures")]
        ),
        .target(name: "LimbIK", dependencies: ["PoseRig"]),
        .testTarget(
            name: "LimbIKTests",
            dependencies: ["LimbIK"],
            resources: [.copy("Fixtures")]
        ),
        .target(name: "StudioContent", resources: [.copy("Resources")]),
        .testTarget(
            name: "StudioContentTests",
            dependencies: ["StudioContent"],
            resources: [.copy("Fixtures")]
        ),
        .target(name: "SceneDocument"),
        .target(name: "Storyboard", dependencies: ["SceneDocument"]),
        .testTarget(
            name: "StoryboardTests",
            dependencies: ["Storyboard"],
            resources: [.copy("Fixtures")]
        ),
        .testTarget(
            name: "SceneDocumentTests",
            dependencies: ["SceneDocument"],
            resources: [.copy("Fixtures")]
        ),
    ]
)
