import { useAcademy, useAcademyContext } from '@/contexts/AcademyContext';
/**
 * Module Manager Component for CreatorHub Academy
 * Advanced module organization and management system
 */

import React, { useState, useCallback, useRef, useEffect } from 'react';
import {
  Box,
  Typography,
  Card,
  CardContent,
  CardActions,
  Button,
  TextField,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  Stack,
  Grid,
  IconButton,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Chip,
  Divider,
  Paper,
  Tooltip,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  List,
  ListItem,
  ListItemText,
  ListItemIcon,
  ListItemSecondaryAction,
  Badge,
  Alert,
  LinearProgress,
  Switch,
  FormControlLabel,
  Slider,
  Avatar,
  Menu,
  MenuList,
  Tab,
  Tabs,
  Stepper,
  Step,
  StepLabel,
  StepContent,
  RadioGroup,
  Radio,
  Checkbox,
  Autocomplete,
  CircularProgress,
  Skeleton,
  Rating,
  ToggleButton,
  ToggleButtonGroup,
  SpeedDial,
  SpeedDialAction,
  SpeedDialIcon,
  Backdrop,
  Drawer,
  AppBar,
  Toolbar,
  Breadcrumbs,
  Link,
} from '@mui/material';
import {
  DndContext,
  closestCenter,
  KeyboardSensor,
  PointerSensor,
  useSensor,
  useSensors,
} from '@dnd-kit/core';
import {
  arrayMove,
  SortableContext,
  sortableKeyboardCoordinates,
  verticalListSortingStrategy,
} from '@dnd-kit/sortable';
import { useSortable } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import {
  Add,
  Edit,
  Delete,
  DragIndicator,
  ExpandMore,
  Visibility,
  VisibilityOff,
  ContentCopy,
  Download,
  Upload,
  PlayArrow,
  Pause,
  Stop,
  Save,
  Close,
  Timeline,
  VideoLibrary,
  Article,
  Quiz,
  Assignment,
  Assessment,
  Bookmark,
  Star,
  StarBorder,
  Lock,
  LockOpen,
  Schedule,
  Timer,
  Group,
  Person,
  School,
  Work,
  Business,
  Celebration,
  AutoAwesome,
  FilterList,
  Sort,
  MoreVert,
  Settings,
  Info,
  Warning,
  CheckCircle,
  RadioButtonUnchecked,
  RadioButtonChecked,
  Description,
  Image as ImageIcon,
  AudioFile,
  History as HistoryIcon,
  Security,
} from '@mui/icons-material';
import {
  AcademyIcon,
  CourseIcon,
  LessonIcon,
  VideoPlayerIcon,
  InstructorIcon,
  StudentIcon,
  LearningPathIcon,
  CertificateIcon,
  QuizIcon,
  BookmarkIcon,
  NoteIcon,
  ContentCreationIcon,
} from '../shared/CreatorHubIcons';
import { useEnhancedMasterIntegration } from '@/integration/EnhancedMasterIntegrationProvider';
import { withUniversalIntegration } from '@/integration/UniversalIntegrationHOC';
import { useTheming } from '../../utils/theming-helper';

// Core Educational Platform Interfaces
interface Asset {
  id: string;
  title: string;
  type: 'video' | 'audio' | 'document' | 'image' | 'interactive' | 'external_link';
  url: string;
  mimeType: string;
  size: number;
  duration?: number; // for video/audio
  thumbnailUrl?: string;
  versions: AssetVersion[];
  metadata: {
    description?: string;
    tags: string[];
    altText?: string;
    transcript?: string;
    captions?: CaptionTrack[];
    chapters?: Chapter[];
  };
  createdAt: string;
  updatedAt: string;
}

interface AssetVersion {
  id: string;
  version: string;
  url: string;
  changes: string[];
  createdBy: string;
  createdAt: string;
  isActive: boolean;
}

interface CaptionTrack {
  id: string;
  language: string;
  url: string;
  isDefault: boolean;
  isAutoGenerated: boolean;
}

interface Chapter {
  id: string;
  title: string;
  startTime: number;
  endTime?: number;
  description?: string;
}

interface Assessment {
  id: string;
  title: string;
  type: 'quiz' | 'assignment' | 'project' | 'discussion' | 'peer_review';
  content: any;
  settings: {
    timeLimit?: number;
    attempts?: number;
    passScore?: number;
    autoGrade?: boolean;
    showFeedback?: boolean;
    allowRetake?: boolean;
  };
  rubric?: Rubric;
  dueDate?: string;
  isRequired: boolean;
  weight: number; // percentage of module grade
}

interface Rubric {
  id: string;
  title: string;
  criteria: RubricCriteria[];
  totalPoints: number;
}

interface RubricCriteria {
  id: string;
  title: string;
  description: string;
  points: number;
  levels: RubricLevel[];
}

interface RubricLevel {
  id: string;
  title: string;
  description: string;
  points: number;
}

interface Entitlement {
  id: string;
  type: 'audience' | 'cohort' | 'role' | 'individual';
  targetId: string;
  permissions: {
    canView: boolean;
    canEdit: boolean;
    canDelete: boolean;
    canPublish: boolean;
    canApprove: boolean;
  };
  conditions?: {
    enrollmentDate?: string;
    completionStatus?: string[];
    customRules?: any;
  };
}

interface Template {
  id: string;
  name: string;
  description: string;
  type: 'module' | 'lesson' | 'assessment' | 'course';
  content: any;
  metadata: {
    tags: string[];
    category: string;
    difficulty: string;
    estimatedTime: number;
  };
  isPublic: boolean;
  createdBy: string;
  usageCount: number;
  rating: number;
  createdAt: string;
  updatedAt: string;
}

interface ReleaseRule {
  id: string;
  type: 'immediate' | 'scheduled' | 'conditional' | 'relative';
  conditions: {
    date?: string;
    relativeDays?: number;
    prerequisites?: string[];
    customRule?: string;
  };
  isActive: boolean;
}

interface CollaborationSettings {
  roles: {
    owner: string[];
    editor: string[];
    reviewer: string[];
    viewer: string[];
  };
  permissions: {
    allowComments: boolean;
    requireApproval: boolean;
    enableLocks: boolean;
    allowVersioning: boolean;
  };
  reviewChecklist: ReviewCriteria[];
}

interface ReviewCriteria {
  id: string;
  title: string;
  description: string;
  category: 'accessibility' | 'content' | 'technical' | 'pedagogical';
  isRequired: boolean;
}

interface ApprovalWorkflow {
  id: string;
  name: string;
  steps: ApprovalStep[];
  isActive: boolean;
}

interface ApprovalStep {
  id: string;
  title: string;
  approverType: 'role' | 'individual' | 'auto';
  approverId: string;
  isRequired: boolean;
  order: number;
}

interface AccessibilityAudit {
  id: string;
  moduleId: string;
  status: 'passed' | 'failed' | 'warning' | 'pending';
  checks: AccessibilityCheck[];
  score: number;
  lastChecked: string;
}

interface AccessibilityCheck {
  id: string;
  type: 'wcag_2_2_aa' | 'wcag_2_2_aaa' | 'section_508' | 'custom';
  criteria: string;
  status: 'passed' | 'failed' | 'warning';
  description: string;
  remediation?: string;
}

interface Module {
  id: string;
  title: string;
  description: string;
  slug: string;
  summary: string;
  objectives: string[];
  type: 'foundation' | 'core' | 'advanced' | 'project' | 'assessment' | 'bonus';
  order: number;
  duration: number; // in minutes
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  isPublished: boolean;
  isLocked: boolean;
  prerequisites: string[]; // Module IDs
  learningOutcomes: string[];
  resources: ModuleResource[];
  lessons: Lesson[];

  // Enhanced Educational Platform Features
  assets: Asset[];
  assessments: Assessment[];
  entitlements: Entitlement[];
  template?: Template;
  versioning: {
    currentVersion: string;
    versions: ModuleVersion[];
    changelog: ChangelogEntry[];
  };
  scheduling: {
    releaseRules: ReleaseRule[];
    expirationDate?: string;
    enrollmentDeadline?: string;
  };
  collaboration: CollaborationSettings;
  approvalWorkflow?: ApprovalWorkflow;
  accessibilityAudit: AccessibilityAudit;
  seo: {
    canonicalUrl?: string;
    metaDescription?: string;
    socialCard?: {
      title?: string;
      description?: string;
      imageUrl?: string;
    };
    embedSettings?: {
      allowEmbedding: boolean;
      allowedDomains: string[];
      requireAttribution: boolean;
    };
  };

  metadata: {
    estimatedTime: number;
    complexity: number; // 1-5 scale
    importance: number; // 1-5 scale
    tags: string[];
    color: string;
    icon: string;
    timeEstimate: number;
    lastAccessed?: string;
    completionRate?: number;
    averageRating?: number;
    enrollmentCount?: number;
  };
  createdAt: string;
  updatedAt: string;
}

interface Lesson {
  id: string;
  title: string;
  description: string;
  type: 'video' | 'text' | 'quiz' | 'assignment' | 'project' | 'discussion';
  duration: number;
  order: number;
  isPreview: boolean;
  isLocked: boolean;
  content: {
    videoUrl?: string;
    textContent?: string;
    quizData?: any;
    assignmentData?: any;
    projectData?: any;
  };
  resources: any[];
  completed: boolean;

  // Enhanced features
  assets: Asset[];
  captions: CaptionTrack[];
  chapters: Chapter[];
  assessments: Assessment[];
  timestampPins: TimestampPin[];
}

interface ModuleResource {
  id: string;
  title: string;
  type: 'document' | 'video' | 'audio' | 'link' | 'template';
  url: string;
  description?: string;
  isRequired: boolean;
}

interface ModuleVersion {
  id: string;
  version: string;
  title: string;
  description: string;
  changes: string[];
  createdBy: string;
  createdAt: string;
  isActive: boolean;
  moduleSnapshot: Partial<Module>;
}

interface ChangelogEntry {
  id: string;
  version: string;
  type: 'added' | 'changed' | 'removed' | 'fixed' | 'security';
  title: string;
  description: string;
  affectedAreas: string[];
  createdBy: string;
  createdAt: string;
}

interface TimestampPin {
  id: string;
  timestamp: number;
  title: string;
  description?: string;
  resourceType: 'slide' | 'reading' | 'external_link' | 'note';
  resourceUrl: string;
  resourceTitle: string;
}

interface ModuleManagerProps {
  courseId?: string;
  modules: Module[];
  onModuleUpdate: (modules: Module[]) => void;
  onModuleSelect?: (module: Module) => void;
  selectedModule?: Module | null;
  mode?: 'create' | 'edit' | 'browse' | 'select';
  showPreview?: boolean;
  height?: number;
}

const MODULE_TYPES = [
  {
    value: 'foundation',
    label: 'Foundation',
    icon: <School />,
    color: '#4caf50',
    description: 'Basic concepts and fundamentals',
  },
  {
    value: 'core',
    label: 'Core Content',
    icon: <VideoLibrary />,
    color: '#2196f3',
    description: 'Main learning content',
  },
  {
    value: 'advanced',
    label: 'Advanced',
    icon: <AutoAwesome />,
    color: '#ff9800',
    description: 'Advanced techniques and concepts',
  },
  {
    value: 'project',
    label: 'Project',
    icon: <Work />,
    color: '#9c27b0',
    description: 'Hands-on project work',
  },
  {
    value: 'assessment',
    label: 'Assessment',
    icon: <Quiz />,
    color: '#f44336',
    description: 'Tests and evaluations',
  },
  {
    value: 'bonus',
    label: 'Bonus',
    icon: <Celebration />,
    color: '#ff5722',
    description: 'Extra content and resources',
  },
];

const LESSON_TYPES = [
  { value: 'video', label: 'Video Lesson', icon: <VideoLibrary />, color: '#2196f3' },
  { value: 'text', label: 'Text Content', icon: <Article />, color: '#4caf50' },
  { value: 'quiz', label: 'Quiz', icon: <Quiz />, color: '#f44336' },
  { value: 'assignment', label: 'Assignment', icon: <Assignment />, color: '#ff9800' },
  { value: 'project', label: 'Project', icon: <Work />, color: '#9c27b0' },
  { value: 'discussion', label: 'Discussion', icon: <Group />, color: '#607d8b' },
];

const SAMPLE_MODULES: Module[] = [
  {
    id: 'mod-1',
    title: 'Photography Fundamentals',
    description:
      'Learn the basic principles of photography including composition, lighting, and camera settings.',
    slug: 'photography-fundamentals',
    summary: 'Essential photography concepts and techniques for beginners',
    objectives: [
      'Master camera basics', 'Learn composition rules','Understand lighting principles',
    ],
    type: 'foundation',
    order: 1,
    duration: 120,
    difficulty: 'beginner',
    isPublished: true,
    isLocked: false,
    prerequisites: [],
    learningOutcomes: [
      'Understand camera basics and settings','Master composition techniques','Learn about lighting fundamentals',
    ],
    assets: [],
    assessments: [],
    entitlements: [],
    resources: [
      {
        id: 'res-1',
        title: 'Camera Settings Cheat Sheet',
        type: 'document',
        url: '/resources/camera-settings.pdf',
        isRequired: true,
      },
    ],
    lessons: [
      {
        id: 'lesson-1',
        title: 'Introduction to Photography',
        description: 'Welcome to the world of photography',
        type: 'video',
        duration: 15,
        order: 1,
        isPreview: true,
        isLocked: false,
        content: { videoUrl: '/videos/intro-photography.mp4' },
        resources: [],
        completed: false,
        assets: [],
        captions: [],
        chapters: [],
        assessments: [],
        timestampPins: [],
      },
    ],
    versioning: {
      currentVersion: '1.0.0',
      versions: [],
      changelog: [],
    },
    scheduling: {
      releaseRules: [],
      expirationDate: undefined,
      enrollmentDeadline: undefined,
    },
    collaboration: {
      roles: { owner: [], editor: [], reviewer: [], viewer: [] },
      permissions: {
        allowComments: true,
        requireApproval: false,
        enableLocks: true,
        allowVersioning: true,
      },
      reviewChecklist: [],
    },
    approvalWorkflow: undefined,
    accessibilityAudit: {
      id: 'audit-1',
      moduleId: 'mod-1',
      status: 'pending',
      checks: [],
      score: 0,
      lastChecked: new Date().toISOString(),
    },
    seo: {
      canonicalUrl: undefined,
      metaDescription: undefined,
      socialCard: undefined,
      embedSettings: undefined,
    },
    metadata: {
      estimatedTime: 120,
      complexity: 2,
      importance: 5,
      tags: ['basics','fundamentals','composition'],
      color: '#4caf50',
      icon: 'school',
      timeEstimate: 120,
    },
    createdAt: '2024-01-15T10:30:00Z',
    updatedAt: '2024-01-15T10:30:00Z',
  },
  {
    id: 'mod-2',
    title: 'Advanced Lighting Techniques',
    description:
      'Master professional lighting setups and techniques for studio and outdoor photography.',
    slug: 'advanced-lighting-techniques',
    summary: 'Professional lighting mastery for studio and outdoor photography',
    objectives: ['Master studio lighting','Understand natural light','Learn advanced techniques'],
    type: 'advanced',
    order: 2,
    duration: 180,
    difficulty: 'advanced',
    isPublished: true,
    isLocked: true,
    prerequisites: ['mod-1'],
    learningOutcomes: [
      'Master studio lighting setups','Understand natural light photography','Learn advanced lighting techniques',
    ],
    assets: [],
    assessments: [],
    entitlements: [],
    resources: [],
    lessons: [],
    versioning: {
      currentVersion: '1.0.0',
      versions: [],
      changelog: [],
    },
    scheduling: {
      releaseRules: [],
      expirationDate: undefined,
      enrollmentDeadline: undefined,
    },
    collaboration: {
      roles: { owner: [], editor: [], reviewer: [], viewer: [] },
      permissions: {
        allowComments: true,
        requireApproval: true,
        enableLocks: true,
        allowVersioning: true,
      },
      reviewChecklist: [],
    },
    approvalWorkflow: undefined,
    accessibilityAudit: {
      id: 'audit-2',
      moduleId: 'mod-2',
      status: 'pending',
      checks: [],
      score: 0,
      lastChecked: new Date().toISOString(),
    },
    seo: {
      canonicalUrl: undefined,
      metaDescription: undefined,
      socialCard: undefined,
      embedSettings: undefined,
    },
    metadata: {
      estimatedTime: 180,
      complexity: 4,
      importance: 4,
      tags: ['lighting','studio','advanced'],
      color: '#ff9800',
      icon: 'auto_awesome',
      timeEstimate: 180,
    },
    createdAt: '2024-01-14T14:20:00Z',
    updatedAt: '2024-01-14T14:20:00Z',
  },
];

function ModuleManager({
  courseId,
  modules,
  onModuleUpdate,
  onModuleSelect,
  selectedModule,
  mode = 'browse',
  showPreview = true,
  height = 600,
}: ModuleManagerProps) {
  const [activeTab, setActiveTab] = useState(0);
  const [showCreateDialog, setShowCreateDialog] = useState(false);
  const [editingModule, setEditingModule] = useState<Module | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [filterType, setFilterType] = useState<string>('all');
  const [filterDifficulty, setFilterDifficulty] = useState<string>('all');
  const [sortBy, setSortBy] = useState<'order' | 'title' | 'duration' | 'difficulty'>('order');
  const [showModuleTemplates, setShowModuleTemplates] = useState(false);
  const [contextMenu, setContextMenu] = useState<{
    mouseX: number;
    mouseY: number;
    module: Module;
  } | null>(null);

  const { analytics, performance, debugging, features } = useEnhancedMasterIntegration();

  // Wire up Academy context
  const academyContext = useAcademyContext();
  const academyState = useAcademy();

  // Theming system
  const theming = useTheming('music_producer');

  // Wire up CreatorHub icons for module types
  const moduleTypeIcons = {
    academy: <AcademyIcon />,
    course: <CourseIcon />,
    lesson: <LessonIcon />,
    video: <VideoPlayerIcon />,
    instructor: <InstructorIcon />,
    student: <StudentIcon />,
    learningPath: <LearningPathIcon />,
    certificate: <CertificateIcon />,
    quiz: <QuizIcon />,
    bookmark: <BookmarkIcon />,
    note: <NoteIcon />,
    content: <ContentCreationIcon />,
  };
  
  // Log module manager initialization
  console.log('Module icons initialized:', Object.keys(moduleTypeIcons).length, 'Academy:', !!academyContext, !!academyState);

  // Comprehensive Feature System for Module Manager
  const moduleManagementAccess = features.checkFeatureAccess('module-management');
  const courseManagementAccess = features.checkFeatureAccess('course-management');
  const contentManagementAccess = features.checkFeatureAccess('content-management');
  const moduleCreationAccess = features.checkFeatureAccess('module-creation');
  const moduleEditingAccess = features.checkFeatureAccess('module-editing');
  const moduleOrganizationAccess = features.checkFeatureAccess('module-organization');
  const moduleAnalyticsAccess = features.checkFeatureAccess('module-analytics');
  const collaborationAccess = features.checkFeatureAccess('collaboration');

  // Track feature usage
  React.useEffect(() => {
    features.trackFeatureUsage('module-management', 'opened', {
      timestamp: Date.now(),
      component: 'ModuleManager',
      courseId: courseId,
      modulesCount: modules.length,
    });
  }, [features, courseId, modules.length]);

  // Filter and sort modules
  const filteredModules = modules
    .filter((module) => {
      const matchesSearch =
        module.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        module.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
        module.metadata.tags.some((tag) => tag.toLowerCase().includes(searchQuery.toLowerCase()));
      const matchesType = filterType === 'all' || module.type === filterType;
      const matchesDifficulty =
        filterDifficulty === 'all' || module.difficulty === filterDifficulty;
      return matchesSearch && matchesType && matchesDifficulty;
    })
    .sort((a, b) => {
      switch (sortBy) {
        case 'title':
          return a.title.localeCompare(b.title);
        case 'duration':
          return b.duration - a.duration;
        case 'difficulty':
          return a.difficulty.localeCompare(b.difficulty);
        default:
          return a.order - b.order;
      }
    });

  // Create new module
  const handleCreateModule = useCallback(() => {
    const newModule: Module = {
      id: `mod-${Date.now()}`,
      title: 'New Module',
      description: 'Enter module description',
      slug: `new-module-${Date.now()}`,
      summary: 'New module summary',
      objectives: [],
      type: 'core',
      order: modules.length + 1,
      duration: 0,
      difficulty: 'beginner',
      isPublished: false,
      isLocked: false,
      prerequisites: [],
      learningOutcomes: [],
      assets: [],
      assessments: [],
      entitlements: [],
      resources: [],
      lessons: [],
      versioning: {
        currentVersion: '1.0.0',
        versions: [],
        changelog: [],
      },
      scheduling: {
        releaseRules: [],
        expirationDate: undefined,
        enrollmentDeadline: undefined,
      },
      collaboration: {
        roles: { owner: [], editor: [], reviewer: [], viewer: [] },
        permissions: {
          allowComments: true,
          requireApproval: false,
          enableLocks: true,
          allowVersioning: true,
        },
        reviewChecklist: [],
      },
      approvalWorkflow: undefined,
      accessibilityAudit: {
        id: `audit-${Date.now()}`,
        moduleId: `mod-${Date.now()}`,
        status: 'pending',
        checks: [],
        score: 0,
        lastChecked: new Date().toISOString(),
      },
      seo: {
        canonicalUrl: undefined,
        metaDescription: undefined,
        socialCard: undefined,
        embedSettings: undefined,
      },
      metadata: {
        estimatedTime: 0,
        complexity: 1,
        importance: 3,
        tags: [],
        color: '#2196f3',
        icon: 'video_library',
        timeEstimate: 0,
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    setEditingModule(newModule);
    setShowCreateDialog(true);
  }, [modules.length]);

  // Save module
  const handleSaveModule = useCallback(
    (module: Module) => {
      const updatedModules = modules.find((m) => m.id === module.id)
        ? modules.map((m) => (m.id === module.id ? module : m))
        : [...modules, module];

      onModuleUpdate(updatedModules);
      setShowCreateDialog(false);
      setEditingModule(null);

      analytics.trackEvent('module_saved', {
        moduleId: module.id,
        moduleTitle: module.title,
        moduleType: module.type,
        courseId,
        timestamp: Date.now(),
      });
    },
    [modules, onModuleUpdate, analytics, courseId],
  );

  // Delete module
  const handleDeleteModule = useCallback(
    (moduleId: string) => {
      const updatedModules = modules.filter((m) => m.id !== moduleId);
      onModuleUpdate(updatedModules);

      analytics.trackEvent('module_deleted', {
        moduleId,
        courseId,
        timestamp: Date.now(),
      });
    },
    [modules, onModuleUpdate, analytics, courseId],
  );

  // Duplicate module
  const handleDuplicateModule = useCallback(
    (module: Module) => {
      const duplicatedModule: Module = {
        ...module,
        id: `mod-${Date.now()}`,
        title: `${module.title} (Copy)`,
        order: modules.length + 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };
      setEditingModule(duplicatedModule);
      setShowCreateDialog(true);
    },
    [modules.length],
  );

  // Drag and drop sensors
  const sensors = useSensors(
    useSensor(PointerSensor),
    useSensor(KeyboardSensor, {
      coordinateGetter: sortableKeyboardCoordinates,
    }),
  );

  // Handle drag end
  const handleDragEnd = useCallback(
    (event: any) => {
      const { active, over } = event;

      if (active.id !== over.id) {
        const oldIndex = modules.findIndex((module) => module.id === active.id);
        const newIndex = modules.findIndex((module) => module.id === over.id);

        const reorderedModules = arrayMove(modules, oldIndex, newIndex);

        // Update order numbers
        const updatedModules = reorderedModules.map((module, index) => ({
          ...module,
          order: index + 1,
          updatedAt: new Date().toISOString(),
        }));

        onModuleUpdate(updatedModules);
      }
    },
    [modules, onModuleUpdate],
  );

  // Get module type info
  const getModuleTypeInfo = (type: string) => {
    return MODULE_TYPES.find((t) => t.value === type) || MODULE_TYPES[0];
  };

  // Get difficulty color
  const getDifficultyColor = (difficulty: string) => {
    switch (difficulty) {
      case 'beginner':
        return '#4caf50';
      case 'intermediate':
        return '#ff9800';
      case 'advanced':
        return '#f44336';
      default:
        return '#757575';
    }
  };

  // Sortable module card component
  const SortableModuleCard = ({ module, index }: { module: Module; index: number }) => {
    const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({
      id: module.id,
    });

    const style = {
      transform: CSS.Transform.toString(transform),
      transition,
      opacity: isDragging ? 0.5 : 1,
    };

    const typeInfo = getModuleTypeInfo(module.type);

    return (
      <Card
        ref={setNodeRef}
        style={style}
        sx={{
          cursor: mode === 'select' ? 'pointer' : 'default',
          border: selectedModule?.id === module.id ? 2 : 1,
          borderColor: selectedModule?.id === module.id ? 'primary.main' : 'divider', '&:hover': { boxShadow: 4 }}}
        onClick={() => mode === 'select' && onModuleSelect?.(module)}
        onContextMenu={(e) => {
          e.preventDefault();
          setContextMenu({
            mouseX: e.clientX + 2,
            mouseY: e.clientY - 6,
            module: module,
          });
        }}
      >
        <CardContent sx={{ p: 2 }}>
          <Stack direction="row" spacing={2} alignItems="flex-start">
            <Box
              sx={{
                width: 48,
                height: 48,
                backgroundColor: typeInfo.color,
                borderRadius: 2,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                color: 'white'}}
            >
              {typeInfo.icon}
            </Box>

            <Box
              {...attributes}
              {...listeners}
              sx={{
                cursor: 'grab',
                display: 'flex',
                alignItems: 'center',
                p: 1, '&:hover': {
                  backgroundColor: 'action.hover',
                  borderRadius: 1,
                }}}
            >
              <DragIndicator color="action" />
            </Box>

            <Box sx={{ flex: 1, minWidth: 0 }}>
              <Stack direction="row" alignItems="center" spacing={1} sx={{ mb: 1 }}>
                <Typography variant="h6" noWrap sx={{ color: theming.colors.primary }}>
                  {module.title}
                </Typography>
                {module.isLocked && <Lock fontSize="small" color="disabled" />}
                {!module.isPublished && <VisibilityOff fontSize="small" color="disabled" />}
              </Stack>

              <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>
                {module.description}
              </Typography>

              <Stack direction="row" spacing={1} sx={{ mb: 1 }}>
                <Chip
                  label={typeInfo.label}
                  size="small"
                  sx={{
                    backgroundColor: typeInfo.color,
                    color: 'white',
                    height: 20,
                    fontSize: 10}}
                />
                <Chip
                  label={module.difficulty}
                  size="small"
                  variant="outlined"
                  sx={{
                    borderColor: getDifficultyColor(module.difficulty),
                    color: getDifficultyColor(module.difficulty),
                    height: 20,
                    fontSize: 10}}
                />
                <Chip
                  label={`${module.duration}min`}
                  size="small"
                  variant="outlined"
                  sx={{ height: 20, fontSize: 10 }}
                />
                <Chip
                  label={`${module.lessons.length} lessons`}
                  size="small"
                  variant="outlined"
                  sx={{ height: 20, fontSize: 10 }}
                />
              </Stack>

              {module.prerequisites.length > 0 && (
                <Typography variant="caption" color="text.secondary">
                  Prerequisites: {module.prerequisites.length} module(s)
                </Typography>
              )}
            </Box>

            <Box sx={{ display: 'flex', alignItems: 'center' }}>
              <IconButton size="small" sx={{ mr: 1 }}>
                <DragIndicator />
              </IconButton>

              {mode !== 'select' && (
                <IconButton
                  size="small"
                  onClick={(e) => {
                    e.stopPropagation();
                    setEditingModule(module);
                    setShowCreateDialog(true);
                  }}
                >
                  <Edit />
                </IconButton>
              )}
            </Box>
          </Stack>
        </CardContent>
      </Card>
    );
  };

  return (
    <Box sx={{ height, display: 'flex', flexDirection: 'column' }}>
      {/* Header */}
      <Box sx={{ borderBottom: 1, borderColor: 'divider', mb: 2 }}>
        <Stack direction="row" alignItems="center" justifyContent="space-between" sx={{ mb: 2 }}>
          <Box>
            <Typography variant="h5" component="h2" sx={{ color: theming.colors.primary }}>
              Module Manager
            </Typography>

            {/* Feature Analytics Display */}
            <Box
              sx={{
                display: 'flex',
                alignItems: 'center',
                gap: 1,
                mt: 0.5}}
            >
              <Typography variant="caption" color="text.secondary">
                Features: {features.getFeatureAnalytics().enabledFeatures}/
                {features.getFeatureAnalytics().totalFeatures}
              </Typography>
              <Chip
                label={`${Math.round(features.getFeatureAnalytics().featureAdoptionRate * 100)}%`}
                size="small"
                variant="outlined"
                sx={{ fontSize: '10px', height: 18 }}
              />
            </Box>
          </Box>
          {mode !== 'select' && (
            <Stack direction="row" spacing={1}>
              <Button variant="outlined" startIcon={<Add />} onClick={handleCreateModule}>
                Create Module
              </Button>
              <Button
                variant="outlined"
                startIcon={<Settings />}
                onClick={() => setShowModuleTemplates(true)}
              >
                Templates
              </Button>
            </Stack>
          )}
        </Stack>

        {/* Search and Filter */}
        <Stack direction="row" spacing={2} sx={{ mb: 2 }}>
          <TextField
            placeholder="Search modules..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            size="small"
            sx={{ flex: 1 }}
          />
          <FormControl size="small" sx={{ minWidth: 120 }}>
            <InputLabel>Type</InputLabel>
            <Select value={filterType} onChange={(e) => setFilterType(e.target.value)} label="Type">
              <MenuItem value="all">All Types</MenuItem>
              {MODULE_TYPES.map((type) => (
                <MenuItem key={type.value} value={type.value}>
                  {type.label}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          <FormControl size="small" sx={{ minWidth: 120 }}>
            <InputLabel>Difficulty</InputLabel>
            <Select
              value={filterDifficulty}
              onChange={(e) => setFilterDifficulty(e.target.value)}
              label="Difficulty"
            >
              <MenuItem value="all">All Levels</MenuItem>
              <MenuItem value="beginner">Beginner</MenuItem>
              <MenuItem value="intermediate">Intermediate</MenuItem>
              <MenuItem value="advanced">Advanced</MenuItem>
            </Select>
          </FormControl>
          <FormControl size="small" sx={{ minWidth: 120 }}>
            <InputLabel>Sort By</InputLabel>
            <Select
              value={sortBy}
              onChange={(e) => setSortBy(e.target.value as any)}
              label="Sort By"
            >
              <MenuItem value="order">Order</MenuItem>
              <MenuItem value="title">Title</MenuItem>
              <MenuItem value="duration">Duration</MenuItem>
              <MenuItem value="difficulty">Difficulty</MenuItem>
            </Select>
          </FormControl>
        </Stack>
      </Box>

      {/* Content */}
      <Box sx={{ flex: 1, overflow: 'auto' }}>
        <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={handleDragEnd}>
          <SortableContext
            items={filteredModules.map((module) => module.id)}
            strategy={verticalListSortingStrategy}
          >
            <Box
              sx={{
                minHeight: 200,
                backgroundColor: 'transparent',
                borderRadius: 1,
                p: 1}}
            >
              {filteredModules.map((module, index) => (
                <SortableModuleCard key={module.id} module={module} index={index} />
              ))}
            </Box>
          </SortableContext>
        </DndContext>

        {filteredModules.length === 0 && (
          <Box sx={{ textAlign: 'center', py: 4 }}>
            <Typography
              variant="h6"
              color="text.secondary"
              gutterBottom
              sx={{ color: theming.colors.primary }}
            >
              No modules found
            </Typography>
            <Typography variant="body2" color="text.secondary">
              Create your first module to organize your course content
            </Typography>
          </Box>
        )}
      </Box>

      {/* Context Menu */}
      <Menu
        open={contextMenu !== null}
        onClose={() => setContextMenu(null)}
        anchorReference="anchorPosition"
        anchorPosition={
          contextMenu !== null ? { top: contextMenu.mouseY, left: contextMenu.mouseX } : undefined
        }
      >
        {contextMenu && (
          <MenuList>
            <MenuItem
              onClick={() => {
                setEditingModule(contextMenu.module);
                setShowCreateDialog(true);
                setContextMenu(null);
              }}
            >
              <ListItemIcon>
                <Edit fontSize="small" />
              </ListItemIcon>
              <ListItemText>Edit Module</ListItemText>
            </MenuItem>
            <MenuItem
              onClick={() => {
                handleDuplicateModule(contextMenu.module);
                setContextMenu(null);
              }}
            >
              <ListItemIcon>
                <ContentCopy fontSize="small" />
              </ListItemIcon>
              <ListItemText>Duplicate Module</ListItemText>
            </MenuItem>
            <Divider />
            <MenuItem
              onClick={() => {
                handleDeleteModule(contextMenu.module.id);
                setContextMenu(null);
              }}
              sx={{ color: 'error.main' }}
            >
              <ListItemIcon>
                <Delete fontSize="small" color="error" />
              </ListItemIcon>
              <ListItemText>Delete Module</ListItemText>
            </MenuItem>
          </MenuList>
        )}
      </Menu>

      {/* Create/Edit Dialog */}
      <Dialog
        open={showCreateDialog}
        onClose={() => setShowCreateDialog(false)}
        maxWidth="md"
        fullWidth
      >
        <DialogTitle>
          {editingModule?.id.startsWith('mod-') && !modules.find((m) => m.id === editingModule.id)
            ? 'Create Module'
            : 'Edit Module'}
        </DialogTitle>
        <DialogContent>
          {editingModule && (
            <ModuleEditor
              module={editingModule}
              onChange={setEditingModule}
              onSave={handleSaveModule}
            />
          )}
        </DialogContent>
      </Dialog>
    </Box>
  );
}

export default withUniversalIntegration(ModuleManager, {
  componentId: 'module-manager',
  componentName: 'Module Manager',
  componentType: 'widget',
  componentCategory: 'academy',
  featureIds: [
    'module-management','course-management','content-management','module-creation','module-editing','module-organization','module-analytics','collaboration',
  ],
});

// Module Editor Component
interface ModuleEditorProps {
  module: Module;
  onChange: (module: Module) => void;
  onSave: (module: Module) => void;
}

function ModuleEditor({ module, onChange, onSave }: ModuleEditorProps) {
  const [activeTab, setActiveTab] = useState(0);
  const theming = useTheming();

  const handleChange = (field: string, value: any) => {
    onChange({
      ...module,
      [field]: value,
      updatedAt: new Date().toISOString(),
    });
  };

  const handleMetadataChange = (field: string, value: any) => {
    onChange({
      ...module,
      metadata: {
        ...module.metadata,
        [field]: value,
      },
      updatedAt: new Date().toISOString(),
    });
  };

  return (
    <Box>
      <Tabs
        value={activeTab}
        onChange={(_, newValue) => setActiveTab(newValue)}
        variant="scrollable"
        scrollButtons="auto"
      >
        <Tab label="Basic Info" />
        <Tab label="Content" />
        <Tab label="Assets" />
        <Tab label="Assessments" />
        <Tab label="Collaboration" />
        <Tab label="Accessibility" />
        <Tab label="Versioning" />
        <Tab label="Scheduling" />
        <Tab label="SEO & Sharing" />
        <Tab label="Entitlements" />
        <Tab label="Settings" />
        <Tab label="Prerequisites" />
      </Tabs>

      {activeTab === 0 && (
        <Box sx={{ mt: 2 }}>
          <TextField
            fullWidth
            label="Module Title"
            value={module.title}
            onChange={(e) => handleChange('title', e.target.value)}
            sx={{ mb: 2 }}
          />
          <TextField
            fullWidth
            label="Description"
            value={module.description}
            onChange={(e) => handleChange('description', e.target.value)}
            multiline
            rows={3}
            sx={{ mb: 2 }}
          />
          <Stack direction="row" spacing={2}>
            <FormControl fullWidth>
              <InputLabel>Module Type</InputLabel>
              <Select
                value={module.type}
                onChange={(e) => handleChange('type', e.target.value)}
                label="Module Type"
              >
                {MODULE_TYPES.map((type) => (
                  <MenuItem key={type.value} value={type.value}>
                    <Stack direction="row" alignItems="center" spacing={1}>
                      {type.icon}
                      <Box>
                        <Typography variant="body2">{type.label}</Typography>
                        <Typography variant="caption" color="text.secondary">
                          {type.description}
                        </Typography>
                      </Box>
                    </Stack>
                  </MenuItem>
                ))}
              </Select>
            </FormControl>
            <FormControl fullWidth>
              <InputLabel>Difficulty</InputLabel>
              <Select
                value={module.difficulty}
                onChange={(e) => handleChange('difficulty', e.target.value)}
                label="Difficulty"
              >
                <MenuItem value="beginner">Beginner</MenuItem>
                <MenuItem value="intermediate">Intermediate</MenuItem>
                <MenuItem value="advanced">Advanced</MenuItem>
              </Select>
            </FormControl>
          </Stack>
        </Box>
      )}

      {activeTab === 1 && (
        <Box sx={{ mt: 2 }}>
          <Typography variant="h6" gutterBottom sx={{ color: theming.colors.primary }}>
            Learning Outcomes
          </Typography>
          <Stack spacing={2}>
            {module.learningOutcomes.map((outcome, index) => (
              <TextField
                key={index}
                fullWidth
                value={outcome}
                onChange={(e) => {
                  const newOutcomes = [...module.learningOutcomes];
                  newOutcomes[index] = e.target.value;
                  handleChange('learningOutcomes', newOutcomes);
                }}
                placeholder="Enter learning outcome"
              />
            ))}
            <Button
              variant="outlined"
              startIcon={<Add />}
              onClick={() => handleChange('learningOutcomes', [...module.learningOutcomes, ','])}
            >
              Add Learning Outcome
            </Button>
          </Stack>
        </Box>
      )}

      {activeTab === 2 && (
        <Box sx={{ mt: 2 }}>
          <Stack spacing={2}>
            <TextField
              label="Duration (minutes)"
              type="number"
              value={module.duration}
              onChange={(e) => handleChange('duration', parseInt(e.target.value) || 0)}
            />
            <FormControlLabel
              control={
                <Switch
                  checked={module.isPublished}
                  onChange={(e) => handleChange('isPublished', e.target.checked)}
                />
              }
              label="Published"
            />
            <FormControlLabel
              control={
                <Switch
                  checked={module.isLocked}
                  onChange={(e) => handleChange('isLocked', e.target.checked)}
                />
              }
              label="Locked (requires prerequisites)"
            />
            <Box>
              <Typography variant="body2" gutterBottom>
                Complexity: {module.metadata.complexity}
              </Typography>
              <Slider
                value={module.metadata.complexity}
                onChange={(_, value) => handleMetadataChange('complexity', value)}
                min={1}
                max={5}
                step={1}
                marks
              />
            </Box>
            <Box>
              <Typography variant="body2" gutterBottom>
                Importance: {module.metadata.importance}
              </Typography>
              <Slider
                value={module.metadata.importance}
                onChange={(_, value) => handleMetadataChange('importance', value)}
                min={1}
                max={5}
                step={1}
                marks
              />
            </Box>
          </Stack>
        </Box>
      )}

      {/* Assets Tab */}
      {activeTab === 2 && (
        <Box sx={{ mt: 2 }}>
          <Typography variant="h6" gutterBottom sx={{ color: theming.colors.primary }}>
            Asset Management
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            Manage videos, documents, images, and other media assets with versioning
          </Typography>

          <Stack spacing={2}>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <Typography variant="subtitle1">Assets ({module.assets.length})</Typography>
              <Button variant="outlined" startIcon={<Add />} size="small">
                Add Asset
              </Button>
            </Box>

            {module.assets.length === 0 ? (
              <Paper sx={{ p: 4, textAlign: 'center', backgroundColor: 'grey.50' }}>
                <Typography variant="body2" color="text.secondary">
                  No assets added yet. Upload videos, documents, or images to enhance your module.
                </Typography>
              </Paper>
            ) : (
              <Stack spacing={1}>
                {module.assets.map((asset) => (
                  <Card key={asset.id} variant="outlined">
                    <CardContent sx={{ p: 2 }}>
                      <Stack direction="row" spacing={2} alignItems="center">
                        <Box
                          sx={{
                            width: 40,
                            height: 40,
                            backgroundColor: 'primary.light',
                            borderRadius: 1,
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center'}}
                        >
                          {asset.type === 'video' && <VideoLibrary />}
                          {asset.type === 'document' && <Description />}
                          {asset.type === 'image' && <ImageIcon />}
                          {asset.type === 'audio' && <AudioFile />}
                        </Box>
                        <Box sx={{ flex: 1 }}>
                          <Typography variant="subtitle2">{asset.title}</Typography>
                          <Typography variant="caption" color="text.secondary">
                            {asset.type} • {asset.versions.length} versions
                          </Typography>
                        </Box>
                        <IconButton size="small">
                          <Edit />
                        </IconButton>
                        <IconButton size="small">
                          <Delete />
                        </IconButton>
                      </Stack>
                    </CardContent>
                  </Card>
                ))}
              </Stack>
            )}
          </Stack>
        </Box>
      )}

      {/* Assessments Tab */}
      {activeTab === 3 && (
        <Box sx={{ mt: 2 }}>
          <Typography variant="h6" gutterBottom sx={{ color: theming.colors.primary }}>
            Assessments & Quizzes
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            Create quizzes, assignments, and projects with rubrics and grading
          </Typography>

          <Stack spacing={2}>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <Typography variant="subtitle1">Assessments ({module.assessments.length})</Typography>
              <Button variant="outlined" startIcon={<Add />} size="small">
                Add Assessment
              </Button>
            </Box>

            {module.assessments.length === 0 ? (
              <Paper sx={{ p: 4, textAlign: 'center', backgroundColor: 'grey.50' }}>
                <Typography variant="body2" color="text.secondary">
                  No assessments added yet. Create quizzes, assignments, or projects to evaluate
                  learning.
                </Typography>
              </Paper>
            ) : (
              <Stack spacing={1}>
                {module.assessments.map((assessment) => (
                  <Card key={assessment.id} variant="outlined">
                    <CardContent sx={{ p: 2 }}>
                      <Stack direction="row" spacing={2} alignItems="center">
                        <Box
                          sx={{
                            width: 40,
                            height: 40,
                            backgroundColor: 'secondary.light',
                            borderRadius: 1,
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center'}}
                        >
                          {assessment.type === 'quiz' && <Quiz />}
                          {assessment.type === 'assignment' && <Assignment />}
                          {assessment.type === 'project' && <Work />}
                        </Box>
                        <Box sx={{ flex: 1 }}>
                          <Typography variant="subtitle2">{assessment.title}</Typography>
                          <Typography variant="caption" color="text.secondary">
                            {assessment.type} • Weight: {assessment.weight}% •{', '}
                            {assessment.isRequired ? 'Required' : 'Optional'}
                          </Typography>
                        </Box>
                        <IconButton size="small">
                          <Edit />
                        </IconButton>
                        <IconButton size="small">
                          <Delete />
                        </IconButton>
                      </Stack>
                    </CardContent>
                  </Card>
                ))}
              </Stack>
            )}
          </Stack>
        </Box>
      )}

      {/* Collaboration Tab */}
      {activeTab === 4 && (
        <Box sx={{ mt: 2 }}>
          <Typography variant="h6" gutterBottom sx={{ color: theming.colors.primary }}>
            Collaboration & Permissions
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            Manage team roles, review processes, and approval workflows
          </Typography>

          <Stack spacing={3}>
            {/* Roles Section */}
            <Box>
              <Typography variant="subtitle1" gutterBottom>
                Team Roles
              </Typography>
              <Grid container spacing={2}>
                <Grid item xs={6}>
                  <FormControl fullWidth>
                    <InputLabel>Owners</InputLabel>
                    <Select multiple value={module.collaboration.roles.owner}>
                      <MenuItem value="user1">John Doe</MenuItem>
                      <MenuItem value="user2">Jane Smith</MenuItem>
                    </Select>
                  </FormControl>
                </Grid>
                <Grid item xs={6}>
                  <FormControl fullWidth>
                    <InputLabel>Editors</InputLabel>
                    <Select multiple value={module.collaboration.roles.editor}>
                      <MenuItem value="user3">Mike Johnson</MenuItem>
                      <MenuItem value="user4">Sarah Wilson</MenuItem>
                    </Select>
                  </FormControl>
                </Grid>
                <Grid item xs={6}>
                  <FormControl fullWidth>
                    <InputLabel>Reviewers</InputLabel>
                    <Select multiple value={module.collaboration.roles.reviewer}>
                      <MenuItem value="user5">Alex Brown</MenuItem>
                    </Select>
                  </FormControl>
                </Grid>
                <Grid item xs={6}>
                  <FormControl fullWidth>
                    <InputLabel>Viewers</InputLabel>
                    <Select multiple value={module.collaboration.roles.viewer}>
                      <MenuItem value="user6">Team Members</MenuItem>
                    </Select>
                  </FormControl>
                </Grid>
              </Grid>
            </Box>

            {/* Permissions Section */}
            <Box>
              <Typography variant="subtitle1" gutterBottom>
                Permissions
              </Typography>
              <Stack spacing={1}>
                <FormControlLabel
                  control={<Switch checked={module.collaboration.permissions.allowComments} />}
                  label="Allow Comments"
                />
                <FormControlLabel
                  control={<Switch checked={module.collaboration.permissions.requireApproval} />}
                  label="Require Approval"
                />
                <FormControlLabel
                  control={<Switch checked={module.collaboration.permissions.enableLocks} />}
                  label="Enable Soft Locks"
                />
                <FormControlLabel
                  control={<Switch checked={module.collaboration.permissions.allowVersioning} />}
                  label="Allow Versioning"
                />
              </Stack>
            </Box>
          </Stack>
        </Box>
      )}

      {/* Accessibility Tab */}
      {activeTab === 5 && (
        <Box sx={{ mt: 2 }}>
          <Typography variant="h6" gutterBottom sx={{ color: theming.colors.primary }}>
            Accessibility & WCAG 2.2 Compliance
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            Ensure your content meets WCAG 2.2 AA standards for accessibility
          </Typography>

          <Stack spacing={2}>
            {/* Accessibility Status */}
            <Paper
              sx={{
                p: 2,
                backgroundColor:
                  module.accessibilityAudit.status === 'passed' ? 'success.light' : 'warning.light'}}
            >
              <Stack direction="row" alignItems="center" spacing={2}>
                <Box>
                  {module.accessibilityAudit.status === 'passed' && <CheckCircle color="success" />}
                  {module.accessibilityAudit.status === 'failed' && <Warning color="error" />}
                  {module.accessibilityAudit.status === 'warning' && <Warning color="warning" />}
                  {module.accessibilityAudit.status === 'pending' && <CircularProgress size={20} />}
                </Box>
                <Box>
                  <Typography variant="subtitle2">
                    Accessibility Status: {module.accessibilityAudit.status.toUpperCase()}
                  </Typography>
                  <Typography variant="caption">
                    Score: {module.accessibilityAudit.score}/100 • Last checked:{', '}
                    {new Date(module.accessibilityAudit.lastChecked).toLocaleDateString()}
                  </Typography>
                </Box>
                <Button variant="outlined" size="small">
                  Run Audit
                </Button>
              </Stack>
            </Paper>

            {/* Accessibility Checklist */}
            <Box>
              <Typography variant="subtitle1" gutterBottom>
                WCAG 2.2 AA Checklist
              </Typography>
              <Stack spacing={1}>
                <FormControlLabel control={<Checkbox />} label="Alt text for all images" />
                <FormControlLabel control={<Checkbox />} label="Captions for all videos" />
                <FormControlLabel control={<Checkbox />} label="Keyboard navigation support" />
                <FormControlLabel control={<Checkbox />} label="Color contrast ratio ≥ 4.5:1" />
                <FormControlLabel control={<Checkbox />} label="Focus indicators visible" />
                <FormControlLabel control={<Checkbox />} label="Screen reader compatibility" />
              </Stack>
            </Box>
          </Stack>
        </Box>
      )}

      {/* Versioning Tab */}
      {activeTab === 6 && (
        <Box sx={{ mt: 2 }}>
          <Typography variant="h6" gutterBottom sx={{ color: theming.colors.primary }}>
            Version History & Rollback
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            Track changes and rollback to previous versions without breaking URLs
          </Typography>

          <Stack spacing={2}>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <Typography variant="subtitle1">
                Current Version: {module.versioning.currentVersion}
              </Typography>
              <Button variant="outlined" startIcon={<HistoryIcon />} size="small">
                View Full History
              </Button>
            </Box>

            {module.versioning.changelog.length === 0 ? (
              <Paper sx={{ p: 4, textAlign: 'center', backgroundColor: 'grey.50' }}>
                <Typography variant="body2" color="text.secondary">
                  No version history available yet. Changes will be tracked automatically.
                </Typography>
              </Paper>
            ) : (
              <Stack spacing={1}>
                {module.versioning.changelog.slice(0, 5).map((entry) => (
                  <Card key={entry.id} variant="outlined">
                    <CardContent sx={{ p: 2 }}>
                      <Stack direction="row" spacing={2} alignItems="center">
                        <Chip
                          label={entry.type}
                          size="small"
                          color={
                            entry.type === 'added'
                              ? 'success'
                              : entry.type === 'changed'
                                ? 'primary': 'default'
                          }
                        />
                        <Box sx={{ flex: 1 }}>
                          <Typography variant="subtitle2">{entry.title}</Typography>
                          <Typography variant="caption" color="text.secondary">
                            {entry.description} • {new Date(entry.createdAt).toLocaleDateString()}
                          </Typography>
                        </Box>
                        <Button size="small" variant="outlined">
                          Restore
                        </Button>
                      </Stack>
                    </CardContent>
                  </Card>
                ))}
              </Stack>
            )}
          </Stack>
        </Box>
      )}

      {/* Scheduling Tab */}
      {activeTab === 7 && (
        <Box sx={{ mt: 2 }}>
          <Typography variant="h6" gutterBottom sx={{ color: theming.colors.primary }}>
            Release Scheduling & Rules
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            Control when and how your module is released to learners
          </Typography>

          <Stack spacing={3}>
            {/* Release Rules */}
            <Box>
              <Typography variant="subtitle1" gutterBottom>
                Release Rules
              </Typography>
              <Stack spacing={2}>
                {module.scheduling.releaseRules.length === 0 ? (
                  <Paper sx={{ p: 2, backgroundColor: 'grey.50' }}>
                    <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>
                      No release rules set. Module will be available immediately.
                    </Typography>
                    <Button variant="outlined" size="small" startIcon={<Add />}>
                      Add Release Rule
                    </Button>
                  </Paper>
                ) : (
                  module.scheduling.releaseRules.map((rule) => (
                    <Card key={rule.id} variant="outlined">
                      <CardContent sx={{ p: 2 }}>
                        <Stack direction="row" justifyContent="space-between" alignItems="center">
                          <Box>
                            <Typography variant="subtitle2">{rule.type}</Typography>
                            <Typography variant="caption" color="text.secondary">
                              {rule.conditions.date &&
                                `Date: ${new Date(rule.conditions.date).toLocaleDateString()}`}
                              {rule.conditions.relativeDays &&
                                `After ${rule.conditions.relativeDays} days`}
                            </Typography>
                          </Box>
                          <IconButton size="small">
                            <Edit />
                          </IconButton>
                        </Stack>
                      </CardContent>
                    </Card>
                  ))
                )}
              </Stack>
            </Box>

            {/* Expiration Settings */}
            <Box>
              <Typography variant="subtitle1" gutterBottom>
                Expiration & Deadlines
              </Typography>
              <Stack spacing={2}>
                <TextField
                  label="Expiration Date"
                  type="date"
                  value={module.scheduling.expirationDate || ''}
                  InputLabelProps={{ shrink: true }}
                />
                <TextField
                  label="Enrollment Deadline"
                  type="date"
                  value={module.scheduling.enrollmentDeadline || ', '}
                  InputLabelProps={{ shrink: true }}
                />
              </Stack>
            </Box>
          </Stack>
        </Box>
      )}

      {/* SEO & Sharing Tab */}
      {activeTab === 8 && (
        <Box sx={{ mt: 2 }}>
          <Typography variant="h6" gutterBottom sx={{ color: theming.colors.primary }}>
            SEO & Sharing Settings
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            Optimize your module for search engines and social sharing
          </Typography>

          <Stack spacing={3}>
            {/* Basic SEO */}
            <Box>
              <Typography variant="subtitle1" gutterBottom>
                Search Engine Optimization
              </Typography>
              <Stack spacing={2}>
                <TextField
                  fullWidth
                  label="Canonical URL"
                  value={module.seo.canonicalUrl || ', '}
                  placeholder="https://example.com/module-slug"
                />
                <TextField
                  fullWidth
                  label="Meta Description"
                  value={module.seo.metaDescription || ', '}
                  multiline
                  rows={2}
                  placeholder="Brief description for search results"
                />
              </Stack>
            </Box>

            {/* Social Sharing */}
            <Box>
              <Typography variant="subtitle1" gutterBottom>
                Social Media Cards
              </Typography>
              <Stack spacing={2}>
                <TextField
                  fullWidth
                  label="Social Card Title"
                  value={module.seo.socialCard?.title || ', '}
                  placeholder="Title for social media shares"
                />
                <TextField
                  fullWidth
                  label="Social Card Description"
                  value={module.seo.socialCard?.description || ', '}
                  multiline
                  rows={2}
                  placeholder="Description for social media shares"
                />
                <TextField
                  fullWidth
                  label="Social Card Image URL"
                  value={module.seo.socialCard?.imageUrl || ''}
                  placeholder="https://example.com/image.jpg"
                />
              </Stack>
            </Box>

            {/* Embed Settings */}
            <Box>
              <Typography variant="subtitle1" gutterBottom>
                Embedding Settings
              </Typography>
              <Stack spacing={2}>
                <FormControlLabel
                  control={<Switch checked={module.seo.embedSettings?.allowEmbedding || false} />}
                  label="Allow Embedding on External Sites"
                />
                <TextField
                  fullWidth
                  label="Allowed Domains"
                  value={module.seo.embedSettings?.allowedDomains?.join('') || ','}
                  placeholder="example.com, mysite.org"
                />
                <FormControlLabel
                  control={
                    <Switch checked={module.seo.embedSettings?.requireAttribution || false} />
                  }
                  label="Require Attribution"
                />
              </Stack>
            </Box>
          </Stack>
        </Box>
      )}

      {/* Entitlements Tab */}
      {activeTab === 9 && (
        <Box sx={{ mt: 2 }}>
          <Typography variant="h6" gutterBottom sx={{ color: theming.colors.primary }}>
            Access Control & Entitlements
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            Control who can access your module and under what conditions
          </Typography>

          <Stack spacing={2}>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <Typography variant="subtitle1">
                Access Rules ({module.entitlements.length})
              </Typography>
              <Button variant="outlined" startIcon={<Add />} size="small">
                Add Access Rule
              </Button>
            </Box>

            {module.entitlements.length === 0 ? (
              <Paper sx={{ p: 4, textAlign: 'center', backgroundColor: 'grey.50' }}>
                <Typography variant="body2" color="text.secondary">
                  No access rules set. Module will be available to all enrolled users.
                </Typography>
              </Paper>
            ) : (
              <Stack spacing={1}>
                {module.entitlements.map((entitlement) => (
                  <Card key={entitlement.id} variant="outlined">
                    <CardContent sx={{ p: 2 }}>
                      <Stack direction="row" spacing={2} alignItems="center">
                        <Box
                          sx={{
                            width: 40,
                            height: 40,
                            backgroundColor: 'info.light',
                            borderRadius: 1,
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center'}}
                        >
                          <Security />
                        </Box>
                        <Box sx={{ flex: 1 }}>
                          <Typography variant="subtitle2">
                            {entitlement.type}: {entitlement.targetId}
                          </Typography>
                          <Typography variant="caption" color="text.secondary">
                            {entitlement.permissions.canView && 'View'}{','}
                            {entitlement.permissions.canEdit && 'Edit'}{', '}
                            {entitlement.permissions.canDelete && 'Delete'}
                          </Typography>
                        </Box>
                        <IconButton size="small">
                          <Edit />
                        </IconButton>
                        <IconButton size="small">
                          <Delete />
                        </IconButton>
                      </Stack>
                    </CardContent>
                  </Card>
                ))}
              </Stack>
            )}
          </Stack>
        </Box>
      )}

      {activeTab === 10 && (
        <Box sx={{ mt: 2 }}>
          <Typography variant="h6" gutterBottom sx={{ color: theming.colors.primary }}>
            Advanced Settings
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            Configure module behavior and technical settings
          </Typography>

          <Stack spacing={3}>
            <Box>
              <Typography variant="subtitle1" gutterBottom>
                Module Configuration
              </Typography>
              <Stack spacing={2}>
                <TextField
                  fullWidth
                  label="Module Slug"
                  value={module.slug}
                  onChange={(e) => handleChange('slug', e.target.value)}
                  placeholder="module-url-slug"
                />
                <TextField
                  fullWidth
                  label="Summary"
                  value={module.summary}
                  onChange={(e) => handleChange('summary', e.target.value)}
                  multiline
                  rows={2}
                  placeholder="Brief summary for course overview"
                />
              </Stack>
            </Box>

            <Box>
              <Typography variant="subtitle1" gutterBottom>
                Learning Objectives
              </Typography>
              <Stack spacing={1}>
                {module.objectives.map((objective, index) => (
                  <TextField
                    key={index}
                    fullWidth
                    value={objective}
                    onChange={(e) => {
                      const newObjectives = [...module.objectives];
                      newObjectives[index] = e.target.value;
                      handleChange('objectives', newObjectives);
                    }}
                    placeholder="Enter learning objective"
                  />
                ))}
                <Button variant="outlined" size="small" startIcon={<Add />}>
                  Add Objective
                </Button>
              </Stack>
            </Box>
          </Stack>
        </Box>
      )}

      {activeTab === 11 && (
        <Box sx={{ mt: 2 }}>
          <Typography variant="h6" gutterBottom sx={{ color: theming.colors.primary }}>
            Prerequisites
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            Select modules that must be completed before this module
          </Typography>
          {/* Prerequisites selection would go here */}
        </Box>
      )}

      <Box sx={{ mt: 3, pt: 2, borderTop: 1, borderColor: 'divider' }}>
        <Button variant="contained" onClick={() => onSave(module)} fullWidth>
          Save Module
        </Button>
      </Box>
    </Box>
  );
}
