import { describe, it, expect } from 'vitest';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  STUDIO_LOCATIONS, DEFAULT_LOCATION_ID, ROLE_WARDROBE,
  facingFor, garmentForRole, insideRoom, resolvePlacement, clearOfCamera, unknownLooks,
  type StudioRole,
} from './studioLocations';
import {
  LIGHTING_LOOKS, DEFAULT_LOOK_ID, STUDIO_KEY_ILLUMINANCE,
  lookKeyIlluminance, fixtureIlluminance,
} from './lightingLooks';
import { ALL_MOVES, buildCameraMove, buildLightMove } from './movePresets';

/**
 * The content, shipped to the native package, and the arithmetic around it.
 *
 * Two files come out of here, and they are different in kind.
 *
 * `Sources/StudioContent/Resources/content.json` is the **content itself** —
 * twelve looks, five places with their marks, twenty named moves. The Swift
 * package decodes it rather than restating it, because these tables are data and
 * hand-copying them would buy nothing and risk a mistyped azimuth that no test
 * would catch, the test having been written from the same typo. Add a look here
 * and it is on the iPad after a regenerate: the same label, the same hint, the
 * same stops.
 *
 * `Tests/StudioContentTests/Fixtures/studioContent.json` is the **golden values**
 * for the functions that are ported as code: where a fixture ends up, which way a
 * person faces, what each move does.
 *
 *   UPDATE_FIXTURES=1 npm test -- studioContent.fixtures
 */

const HERE = dirname(fileURLToPath(import.meta.url));
const CONTENT = resolve(HERE, '../../apple/VirtualstudioCore/Sources/StudioContent/Resources/content.json');
const FIXTURE = resolve(HERE, '../../apple/VirtualstudioCore/Tests/StudioContentTests/Fixtures/studioContent.json');

/** Marks from every place at once, so `facesMark` is resolved across rooms too. */
const ALL_MARKS = STUDIO_LOCATIONS.flatMap(location => location.marks ?? []);

/** One built cue: a camera move carries the shot, a light move its output. */
interface CueCase {
  move: string;
  shot: string;
  camera?: { position: { x: number; y: number; z: number }; target: { x: number; y: number; z: number } };
  intensity?: number;
  cue: ReturnType<typeof buildCameraMove>;
}

const SUBJECTS = [
  { name: 'an adult in the middle of the room', subject: { x: 0, z: 0, eyeHeight: 1.61 } },
  { name: 'a child, off to one side', subject: { x: -0.8, z: 0.4, eyeHeight: 1.12 } },
  { name: 'someone seated', subject: { x: 0.3, z: -1.5, eyeHeight: 1.18 } },
];

const CAMERAS = [
  { name: 'in front', camera: { x: 0, y: 1.5, z: -4 } },
  { name: 'round to the side', camera: { x: 3.4, y: 1.5, z: -1.2 } },
  { name: 'behind the subject', camera: { x: 0, y: 1.5, z: 4 } },
];

function buildContent() {
  return {
    source: 'src/services/studioLocations.ts, lightingLooks.ts, movePresets.ts',
    note: 'Generated by studioContent.fixtures.test.ts. Decoded by StudioContent in apple/VirtualstudioCore.',
    defaultLocationId: DEFAULT_LOCATION_ID,
    defaultLookId: DEFAULT_LOOK_ID,
    studioKeyIlluminance: STUDIO_KEY_ILLUMINANCE,
    locations: STUDIO_LOCATIONS,
    looks: LIGHTING_LOOKS,
    moves: ALL_MOVES,
    roleWardrobe: ROLE_WARDROBE,
  };
}

function buildFixture() {
  return {
    source: 'src/services/studioLocations.ts, lightingLooks.ts, movePresets.ts',
    note: 'Generated by studioContent.fixtures.test.ts. Read by StudioContentTests.',
    // Which way every person in every place ends up facing.
    facing: STUDIO_LOCATIONS.flatMap(location =>
      (location.marks ?? []).map(mark => ({
        location: location.id, mark: mark.id,
        radians: facingFor(mark, location.marks ?? []),
        // And against the whole set of marks, which is what a staffed scene does.
        radiansAcrossAll: facingFor(mark, ALL_MARKS),
      }))),
    // What each role puts on, out of wardrobes that have it and wardrobes that do not.
    wardrobe: (Object.keys(ROLE_WARDROBE) as StudioRole[]).flatMap(role => [
      { role, available: ['female_worksuit01', 'female_elegantsuit01', 'shoes01'] },
      { role, available: ['male_casualsuit01', 'shoes02'] },
      { role, available: ['something_else'] },
      { role, available: [] as string[] },
    ].map(entry => ({ ...entry, garment: garmentForRole(entry.role, entry.available) ?? null }))),
    // Every look's fixtures resolved in every room, from every camera, for every
    // subject — walked inside the walls and swung clear of the lens.
    placement: LIGHTING_LOOKS.flatMap(look =>
      look.fixtures.filter(f => f.placement).flatMap(fixture =>
        SUBJECTS.flatMap(({ name: subjectName, subject }) =>
          CAMERAS.map(({ name: cameraName, camera }) => {
            const resolved = resolvePlacement(fixture.placement!, subject, camera);
            const clear = clearOfCamera(resolved.position, resolved.aim, camera);
            const location = STUDIO_LOCATIONS.find(l => l.look === look.id && l.bounds);
            const walked = location?.bounds
              ? insideRoom(clear, resolved.aim, location.bounds)
              : clear;
            return {
              look: look.id, fixture: fixture.name, subject: subjectName, camera: cameraName,
              placement: fixture.placement, subjectStand: subject, cameraAt: camera,
              bounds: location?.bounds ?? null,
              resolved: resolved.position, aim: resolved.aim, clear, walked,
              illuminance: fixtureIlluminance(look, fixture),
            };
          })))),
    // The key reading each look asks for.
    keyIlluminance: LIGHTING_LOOKS.map(look => ({
      look: look.id, keyStops: look.keyStops, lux: lookKeyIlluminance(look),
    })),
    // Every move, built against two different shots.
    cues: ALL_MOVES.flatMap((move): CueCase[] => {
      const shots = [
        { name: 'a tight portrait', camera: { position: { x: 0, y: 1.55, z: -2.4 }, target: { x: 0, y: 1.5, z: 0 } } },
        { name: 'a wide of the room', camera: { position: { x: -4, y: 2.2, z: -7.5 }, target: { x: 0.4, y: 1.2, z: 0.6 } } },
      ];
      if (move.kind === 'camera') {
        return shots.map(({ name, camera }) => ({
          move: move.id, shot: name, camera,
          cue: buildCameraMove(move.id, {
            id: `cue-${move.id}`, start: 1.5, duration: 4, camera, cameraNodeId: 'takingCamera',
          }),
        }));
      }
      return [0.8, 0.05, 0].map(intensity => ({
        move: move.id, shot: `light at ${intensity}`, intensity,
        cue: buildLightMove(move.id, {
          id: `cue-${move.id}`, start: 1.5, duration: 4,
          lightNodeId: 'light_key', intensity, color: { x: 1, y: 0.95, z: 0.9 },
        }),
      }));
    }),
    // An unknown name is refused rather than answered with an empty cue.
    unknownMoves: ['zoom-in', 'strobe', ''].map(id => ({
      id,
      camera: buildCameraMove(id, {
        id: 'cue-x', start: 0, duration: 1,
        camera: { position: { x: 0, y: 1.5, z: -3 }, target: { x: 0, y: 1.5, z: 0 } },
        cameraNodeId: 'takingCamera',
      }),
      light: buildLightMove(id, {
        id: 'cue-x', start: 0, duration: 1,
        lightNodeId: 'light_key', intensity: 0.8, color: { x: 1, y: 1, z: 1 },
      }),
    })),
  };
}

describe('the places, the looks and the moves, for both editions', () => {
  it('ships the content the Swift package decodes', () => {
    const current = buildContent();
    if (process.env.UPDATE_FIXTURES) {
      mkdirSync(dirname(CONTENT), { recursive: true });
      writeFileSync(CONTENT, `${JSON.stringify(current, null, 2)}\n`);
    }
    expect(JSON.parse(JSON.stringify(current))).toEqual(JSON.parse(readFileSync(CONTENT, 'utf8')));
  });

  it('matches the fixture the Swift suite reads', () => {
    const current = buildFixture();
    if (process.env.UPDATE_FIXTURES) {
      mkdirSync(dirname(FIXTURE), { recursive: true });
      writeFileSync(FIXTURE, `${JSON.stringify(current, null, 2)}\n`);
    }
    expect(JSON.parse(JSON.stringify(current))).toEqual(JSON.parse(readFileSync(FIXTURE, 'utf8')));
  });

  it('asks the room for a look that exists, everywhere', () => {
    // A place naming a look the catalogue does not have would arrive unlit, and
    // the native edition would arrive unlit in exactly the same way.
    expect(unknownLooks()).toEqual([]);
  });

  it('walks a light inside every room it is used in', () => {
    // The property, not a golden value: no fixture may end up outside the walls
    // of the place its look belongs to.
    for (const entry of buildFixture().placement) {
      if (!entry.bounds) continue;
      expect(Math.abs(entry.walked.x), `${entry.look} · ${entry.fixture}`)
        .toBeLessThanOrEqual(entry.bounds.halfWidth + 1e-9);
      expect(Math.abs(entry.walked.z), `${entry.look} · ${entry.fixture}`)
        .toBeLessThanOrEqual(entry.bounds.halfDepth + 1e-9);
      expect(entry.walked.y, `${entry.look} · ${entry.fixture}`)
        .toBeLessThanOrEqual(entry.bounds.height + 1e-9);
    }
  });
});
