import { describe, it, expect } from 'vitest';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { bodyIndicesWearing } from './wardrobeService';

/**
 * Which body triangles survive a change of clothes, for both editions.
 *
 * The web renderer rebuilds the whole index buffer whenever a garment changes.
 * A native renderer does not have to: a garment hides *sorted ranges* of
 * triangles, so what is left is a handful of runs, and a run is exactly what a
 * `LowLevelMesh.Part` is. Changing clothes becomes a change of parts over one
 * buffer instead of a new buffer every time.
 *
 * That is a different implementation of the same rule, which is precisely when
 * the two can drift apart without anybody noticing — a wrong run leaves a hole in
 * a figure, or a sleeve drawn over bare skin. So the runs are computed here from
 * the web implementation and asserted in Swift against the same file.
 *
 *   UPDATE_FIXTURES=1 npm test -- wardrobeParts.fixtures
 */

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURE = resolve(HERE, '../../apple/VirtualstudioCore/Tests/StudioAssetsTests/Fixtures/wardrobeParts.json');
const WARDROBE = resolve(HERE, '../../public/models/avatars/studio/wardrobe.json');

/** The runs of visible triangles, as mesh parts over the original buffer. */
function partsOf(triangleCount: number, ranges: [number, number][]) {
  // Straight through the web implementation: build the kept index list the way
  // the browser does, then read the runs back out of it. Deriving the runs from
  // the ranges directly would be a second implementation, and then the fixture
  // would only be asserting that the second one agrees with the third.
  const full = Array.from({ length: triangleCount * 3 }, (_, i) => i);
  const kept = bodyIndicesWearing(full, [{ hidesBodyTriangles: ranges }]);
  const parts: { indexOffset: number; indexCount: number }[] = [];
  for (let at = 0; at < kept.length; at += 3) {
    const offset = kept[at];
    const last = parts[parts.length - 1];
    if (last && last.indexOffset + last.indexCount === offset) last.indexCount += 3;
    else parts.push({ indexOffset: offset, indexCount: 3 });
  }
  return { keptTriangles: kept.length / 3, parts };
}

const SYNTHETIC: { name: string; triangleCount: number; ranges: [number, number][] }[] = [
  { name: 'nothing worn', triangleCount: 10, ranges: [] },
  { name: 'a hole in the middle', triangleCount: 10, ranges: [[3, 6]] },
  { name: 'covered from the start', triangleCount: 10, ranges: [[0, 4]] },
  { name: 'covered to the end', triangleCount: 10, ranges: [[6, 10]] },
  { name: 'covered entirely', triangleCount: 10, ranges: [[0, 10]] },
  { name: 'two holes', triangleCount: 12, ranges: [[2, 4], [8, 10]] },
  { name: 'overlapping ranges', triangleCount: 12, ranges: [[2, 6], [4, 8]] },
  { name: 'ranges out of order', triangleCount: 12, ranges: [[8, 10], [2, 4]] },
  { name: 'a range past the end', triangleCount: 10, ranges: [[8, 40]] },
  { name: 'a range before the start', triangleCount: 10, ranges: [[-5, 3]] },
  { name: 'a backwards range', triangleCount: 10, ranges: [[7, 2]] },
  { name: 'an empty range', triangleCount: 10, ranges: [[4, 4]] },
  { name: 'no triangles at all', triangleCount: 0, ranges: [[0, 4]] },
];

function build() {
  const real: { name: string; triangleCount: number; ranges: [number, number][] }[] = [];
  if (existsSync(WARDROBE)) {
    // The actual garments, which are the case that matters: a hundred-odd ranges
    // each, and the body is 26 756 triangles.
    const catalogue = JSON.parse(readFileSync(WARDROBE, 'utf8'));
    for (const garment of catalogue.garments) {
      real.push({
        name: `${garment.body} · ${garment.id}`,
        triangleCount: garment.bodyTriangles,
        ranges: garment.hidesBodyTriangles,
      });
    }
  }

  return {
    source: 'src/services/wardrobeService.ts',
    note: 'Generated by wardrobeParts.fixtures.test.ts. Read by StudioAssetsTests in apple/VirtualstudioCore.',
    cases: [...SYNTHETIC, ...real].map(entry => ({ ...entry, ...partsOf(entry.triangleCount, entry.ranges) })),
  };
}

describe('what is left of a body when it has clothes on', () => {
  it('matches the fixture the Swift suite reads', () => {
    const current = build();
    if (process.env.UPDATE_FIXTURES) {
      mkdirSync(dirname(FIXTURE), { recursive: true });
      writeFileSync(FIXTURE, `${JSON.stringify(current, null, 2)}\n`);
    }
    expect(JSON.parse(JSON.stringify(current))).toEqual(JSON.parse(readFileSync(FIXTURE, 'utf8')));
  });

  it('keeps every triangle no garment covers, and no others', () => {
    // The property, whatever the runs turn out to be: the parts must add up to
    // the kept triangles exactly.
    for (const entry of build().cases) {
      const drawn = entry.parts.reduce((total, part) => total + part.indexCount, 0);
      expect(drawn, entry.name).toBe(entry.keptTriangles * 3);
    }
  });
});
