import Foundation
import Testing
@testable import Photometry

/// The Swift port, checked against the numbers the web studio produces.
///
/// Every case here comes from `Fixtures/photometry.json`, which is generated by
/// `src/core/rendering/photometry.fixtures.test.ts` from the TypeScript
/// implementation. Nothing in this file states what the right answer is; the
/// point is that the two editions agree, so that one scene document describes
/// one photograph on both.
///
/// The tolerance is relative and 1e-12: far below any photographic meaning, and
/// still tight enough that a real divergence in the arithmetic cannot hide in
/// it. Transcendental functions are allowed to disagree in their last bits
/// between two standard libraries; a wrong formula is not.
private let tolerance = 1e-12

private func expectClose(
    _ actual: Double,
    _ expected: Double,
    _ label: String,
    sourceLocation: SourceLocation = #_sourceLocation
) {
    let scale = max(abs(expected), 1)
    #expect(
        abs(actual - expected) <= tolerance * scale,
        "\(label): got \(actual), fixture says \(expected)",
        sourceLocation: sourceLocation
    )
}

// MARK: - The fixture file

private struct Fixture: Decodable {
    struct Constants: Decodable {
        let INCIDENT_METER_CONSTANT_C: Double
        let SCENE_INTENSITY_PER_CANDELA: Double
        let DEFAULT_BEAM_ANGLE_DEG: Double
        let REFERENCE_SHUTTER_SECONDS: Double
        let MAX_SPOT_CONE_RAD: Double
    }
    struct FlashType: Decodable { let type: String; let flash: Bool }
    struct Cone: Decodable { let beamAngleDeg: Double; let radians: Double }
    struct Solid: Decodable { let beamAngleDeg: Double; let steradian: Double }
    struct Spec: Decodable {
        let lux1m: Double?
        let lumens: Double?
        let beamAngleDeg: Double?
        let guideNumber: Double?
        let type: String?
    }
    struct Candela: Decodable { let name: String; let spec: Spec; let candela: Double? }
    struct Illuminance: Decodable { let candela: Double; let metres: Double; let lux: Double }
    struct Distance: Decodable { let candela: Double; let lux: Double; let metres: Double }
    struct Stops: Decodable { let from: Double; let to: Double; let stops: Double }
    struct EV: Decodable { let lux: Double; let ev: Double }
    struct Aperture: Decodable { let lux: Double; let iso: Double; let shutterSeconds: Double; let aperture: Double }
    struct FlashExposure: Decodable { let guideNumber: Double; let luxSeconds: Double }
    struct FlashCandela: Decodable { let guideNumber: Double; let shutterSeconds: Double; let candela: Double }
    struct Compensation: Decodable { let shutterSeconds: Double; let factor: Double }
    struct FlashAperture: Decodable { let guideNumber: Double; let metres: Double; let iso: Double; let aperture: Double }
    struct Intensity: Decodable { let candela: Double; let intensity: Double }
    struct Size: Decodable { let label: String; let glbFile: String?; let metres: Double }
    struct Rectangle: Decodable { let label: String; let glbFile: String?; let width: Double; let height: Double }
    struct Hardening: Decodable { let sourceSizeMetres: Double; let beamAngleRad: Double; let ratio: Double }

    let source: String
    let constants: Constants
    let isFlashFixture: [FlashType]
    let spotConeRadians: [Cone]
    let coneSolidAngle: [Solid]
    let fixtureCandela: [Candela]
    let illuminanceAt: [Illuminance]
    let distanceForIlluminance: [Distance]
    let stopsBetween: [Stops]
    let evAtIso100: [EV]
    let apertureForIlluminance: [Aperture]
    let flashLuminousExposureAt1m: [FlashExposure]
    let flashEquivalentCandela: [FlashCandela]
    let flashShutterCompensation: [Compensation]
    let flashApertureAt: [FlashAperture]
    let sceneIntensityFromCandela: [Intensity]
    let modifierSizeMetres: [Size]
    let modifierRectangleMetres: [Rectangle]
    let contactHardeningRatio: [Hardening]
}

private let fixture: Fixture = {
    guard let url = Bundle.module.url(forResource: "photometry", withExtension: "json", subdirectory: "Fixtures") else {
        fatalError("photometry.json is missing. Generate it with UPDATE_FIXTURES=1 npm test -- photometry.fixtures")
    }
    // swiftlint:disable:next force_try
    return try! JSONDecoder().decode(Fixture.self, from: Data(contentsOf: url))
}()

// MARK: - The constants

@Test("the calibration constants are the same numbers")
func constantsMatch() {
    expectClose(INCIDENT_METER_CONSTANT_C, fixture.constants.INCIDENT_METER_CONSTANT_C, "C")
    expectClose(SCENE_INTENSITY_PER_CANDELA, fixture.constants.SCENE_INTENSITY_PER_CANDELA, "intensity per candela")
    expectClose(DEFAULT_BEAM_ANGLE_DEG, fixture.constants.DEFAULT_BEAM_ANGLE_DEG, "default beam")
    expectClose(REFERENCE_SHUTTER_SECONDS, fixture.constants.REFERENCE_SHUTTER_SECONDS, "reference shutter")
    expectClose(MAX_SPOT_CONE_RAD, fixture.constants.MAX_SPOT_CONE_RAD, "max cone")
}

// MARK: - A fixture's output

@Test("a flash is told apart from a continuous source the same way")
func flashTypes() {
    for row in fixture.isFlashFixture {
        #expect(isFlashFixture(row.type) == row.flash, "\(row.type)")
    }
}

@Test("a published beam angle becomes the same cone, capped the same way")
func cones() throws {
    for row in fixture.spotConeRadians {
        expectClose(try spotConeRadians(row.beamAngleDeg), row.radians, "\(row.beamAngleDeg)°")
    }
}

@Test("a beam spreads over the same solid angle")
func solidAngles() throws {
    for row in fixture.coneSolidAngle {
        expectClose(try coneSolidAngle(row.beamAngleDeg), row.steradian, "\(row.beamAngleDeg)°")
    }
}

@Test("every catalogue fixture reports the same candela, including none at all")
func candela() throws {
    for row in fixture.fixtureCandela {
        let spec = FixturePhotometrics(
            lux1m: row.spec.lux1m,
            lumens: row.spec.lumens,
            beamAngleDeg: row.spec.beamAngleDeg,
            guideNumber: row.spec.guideNumber,
            type: row.spec.type
        )
        let actual = try fixtureCandela(spec)
        switch (actual, row.candela) {
        case let (value?, expected?): expectClose(value, expected, row.name)
        case (nil, nil): break
        default: Issue.record("\(row.name): got \(String(describing: actual)), fixture says \(String(describing: row.candela))")
        }
    }
}

// MARK: - What arrives at the subject

@Test("illuminance falls off identically, and holds at the minimum distance")
func illuminance() throws {
    for row in fixture.illuminanceAt {
        expectClose(try illuminanceAt(row.candela, metres: row.metres), row.lux, "\(row.candela) cd at \(row.metres) m")
    }
}

@Test("the distance for a wanted reading is the same distance")
func distances() throws {
    for row in fixture.distanceForIlluminance {
        expectClose(try distanceForIlluminance(row.candela, lux: row.lux), row.metres, "\(row.candela) cd → \(row.lux) lx")
    }
}

@Test("stops between two readings agree")
func stops() throws {
    for row in fixture.stopsBetween {
        expectClose(try stopsBetween(row.from, row.to), row.stops, "\(row.from) → \(row.to)")
    }
}

@Test("the meter reads the same EV and the same aperture")
func metering() throws {
    for row in fixture.evAtIso100 {
        expectClose(try evAtIso100(row.lux), row.ev, "\(row.lux) lx")
    }
    for row in fixture.apertureForIlluminance {
        expectClose(
            try apertureForIlluminance(row.lux, iso: row.iso, shutterSeconds: row.shutterSeconds),
            row.aperture,
            "\(row.lux) lx at ISO \(row.iso)"
        )
    }
}

// MARK: - Flash

@Test("a guide number becomes the same exposure, candela and aperture")
func flash() throws {
    for row in fixture.flashLuminousExposureAt1m {
        expectClose(try flashLuminousExposureAt1m(row.guideNumber), row.luxSeconds, "GN \(row.guideNumber)")
    }
    for row in fixture.flashEquivalentCandela {
        expectClose(
            try flashEquivalentCandela(row.guideNumber, shutterSeconds: row.shutterSeconds),
            row.candela,
            "GN \(row.guideNumber) at \(row.shutterSeconds) s"
        )
    }
    for row in fixture.flashShutterCompensation {
        expectClose(try flashShutterCompensation(row.shutterSeconds), row.factor, "\(row.shutterSeconds) s")
    }
    for row in fixture.flashApertureAt {
        expectClose(
            try flashApertureAt(row.guideNumber, metres: row.metres, iso: row.iso),
            row.aperture,
            "GN \(row.guideNumber) at \(row.metres) m"
        )
    }
}

// MARK: - Scene intensity

@Test("candela maps to scene intensity linearly, with no ceiling")
func intensity() throws {
    for row in fixture.sceneIntensityFromCandela {
        expectClose(try sceneIntensityFromCandela(row.candela), row.intensity, "\(row.candela) cd")
    }
    // The bug this replaced: a clamp that made every bright fixture identical.
    let bright = try sceneIntensityFromCandela(900_000)
    let brighter = try sceneIntensityFromCandela(1_800_000)
    expectClose(brighter / bright, 2, "doubling candela doubles intensity")
}

// MARK: - Modifiers

@Test("every catalogue label measures the same modifier")
func modifierSizes() {
    for row in fixture.modifierSizeMetres {
        expectClose(modifierSizeMetres(row.label, glbFile: row.glbFile), row.metres, row.label)
    }
    for row in fixture.modifierRectangleMetres {
        let rect = modifierRectangleMetres(row.label, glbFile: row.glbFile)
        expectClose(rect.width, row.width, "\(row.label) width")
        expectClose(rect.height, row.height, "\(row.label) height")
    }
}

@Test("the penumbra is built from the modifier's real size")
func hardening() throws {
    for row in fixture.contactHardeningRatio {
        expectClose(
            try contactHardeningRatio(sourceSizeMetres: row.sourceSizeMetres, beamAngleRad: row.beamAngleRad),
            row.ratio,
            "\(row.sourceSizeMetres) m at \(row.beamAngleRad) rad"
        )
    }
}

@Test("a stripbox stays crisper than a softbox, which is the whole claim")
func stripboxIsCrisper() throws {
    let beam = try spotConeRadians(55)
    let strip = try contactHardeningRatio(sourceSizeMetres: modifierSizeMetres("Stripbox 30×120 cm"), beamAngleRad: beam)
    let soft = try contactHardeningRatio(sourceSizeMetres: modifierSizeMetres("Softboks 90×120 cm"), beamAngleRad: beam)
    #expect(strip < soft)
}

// MARK: - What it refuses

@Test("invalid input is refused rather than answered")
func refusals() {
    #expect(throws: PhotometryError.self) { try spotConeRadians(0) }
    #expect(throws: PhotometryError.self) { try spotConeRadians(.nan) }
    #expect(throws: PhotometryError.self) { try coneSolidAngle(-10) }
    #expect(throws: PhotometryError.self) { try flashLuminousExposureAt1m(0) }
    #expect(throws: PhotometryError.self) { try flashEquivalentCandela(58, shutterSeconds: 0) }
    #expect(throws: PhotometryError.self) { try flashShutterCompensation(0) }
    #expect(throws: PhotometryError.self) { try illuminanceAt(-1, metres: 2) }
    #expect(throws: PhotometryError.self) { try distanceForIlluminance(45000, lux: 0) }
    #expect(throws: PhotometryError.self) { try stopsBetween(0, 100) }
    #expect(throws: PhotometryError.self) { try evAtIso100(0) }
    #expect(throws: PhotometryError.self) { try apertureForIlluminance(5000, iso: 0, shutterSeconds: 1) }
    #expect(throws: PhotometryError.self) { try apertureForIlluminance(5000, iso: 100, shutterSeconds: .infinity) }
    #expect(throws: PhotometryError.self) { try sceneIntensityFromCandela(.nan) }
    #expect(throws: PhotometryError.self) { try contactHardeningRatio(sourceSizeMetres: 0, beamAngleRad: 1) }
    // A cone cannot open to π, so the clamped maximum is what a spot may use.
    #expect(throws: PhotometryError.self) { try contactHardeningRatio(sourceSizeMetres: 0.9, beamAngleRad: .pi) }
    #expect(throws: Never.self) { try contactHardeningRatio(sourceSizeMetres: 0.9, beamAngleRad: MAX_SPOT_CONE_RAD) }
}
