/**
 * Demo Scenes - Multiple vector-based shot planning scenes
 * 
 * Different room types and layouts for various filming scenarios:
 * - The Safehouse (living room)
 * - Corporate Boardroom (office)
 * - Master Bedroom (intimate)
 * - Kitchen & Dining (domestic)
 * - Industrial Warehouse (large space)
 * - Restaurant/Bar (public venue)
 * - Hospital Room (clinical)
 * - Luxury Penthouse (modern)
 */

import { Scene2D } from './types';

// =============================================================================
// SCENE 1: The Safehouse (Living Room - INT. SAFEHOUSE - NIGHT)
// =============================================================================

export const createSafehouseScene = (): Scene2D => {
  const sceneWidth = 900;
  const sceneHeight = 700;
  const pixelsPerMeter = 10;
  
  return {
    id: 'scene-safehouse',
    name: 'Scene 12: The Safehouse',
    description: 'INT. SAFEHOUSE - NIGHT',
    location: 'Interior Safehouse',
    
    floorPlan: {
      id: 'floorplan-safehouse',
      name: 'Safehouse Layout',
      imageUrl: '',
      rooms: [],
      gridSize: 60,
      showGrid: false,
      gridOpacity: 0.2,
      scale: pixelsPerMeter,
      bounds: { x: 0, y: 0, width: sceneWidth, height: sceneHeight },
    },
    
    cameras: [
      {
        id: 'cam-a',
        name: 'Cam A',
        label: 'Cam A',
        position: { x: 200, y: 300 },
        rotation: 45,
        color: '#FFD700',
        shotType: 'WS',
        lens: '24mm',
        height: 'Eye Level',
        angle: 'Straight On',
        movement: 'Static',
        frustum: { nearDistance: 5, farDistance: 10, fov: 84 },
        showFrustum: true,
        frustumOpacity: 0.25,
        isSelected: false,
        isActive: true,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'cam-b',
        name: 'Cam B',
        label: 'Cam B',
        position: { x: 750, y: 280 },
        rotation: 180,
        color: '#4FC3F7',
        shotType: 'MS',
        lens: '35mm',
        height: 'Eye Level',
        angle: 'Straight On',
        movement: 'Static',
        frustum: { nearDistance: 4, farDistance: 8, fov: 63 },
        showFrustum: true,
        frustumOpacity: 0.25,
        isSelected: false,
        isActive: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'cam-c',
        name: 'Cam C',
        label: 'Cam C',
        position: { x: 550, y: 520 },
        rotation: -45,
        color: '#81C784',
        shotType: 'CU',
        lens: '50mm',
        height: 'Eye Level',
        angle: 'Straight On',
        movement: 'Static',
        frustum: { nearDistance: 3, farDistance: 6, fov: 46 },
        showFrustum: true,
        frustumOpacity: 0.25,
        isSelected: false,
        isActive: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
    ],
    
    actors: [
      {
        id: 'actor-1',
        name: 'Character 1',
        characterName: 'Alex',
        position: { x: 450, y: 330 },
        rotation: 0,
        scale: 1,
        color: '#2D3748',
        pose: 'Standing',
        facing: '3/4 Back Right',
        showMovementPath: false,
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'actor-2',
        name: 'Character 2',
        characterName: 'Blake',
        position: { x: 530, y: 350 },
        rotation: 0,
        scale: 1,
        color: '#374151',
        pose: 'Standing',
        facing: '3/4 Front Left',
        showMovementPath: false,
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'actor-3',
        name: 'Character 3',
        characterName: 'Charlie',
        position: { x: 620, y: 310 },
        rotation: 0,
        scale: 1,
        color: '#1F2937',
        pose: 'Standing',
        facing: 'Right',
        showMovementPath: false,
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
    ],
    
    props: [
      {
        id: 'prop-sofa',
        name: 'Sofa',
        category: 'Furniture',
        position: { x: 450, y: 180 },
        rotation: 0,
        scale: 1,
        size: { width: 200, height: 80 },
        color: '#6B7280',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-coffee-table',
        name: 'Coffee Table',
        category: 'Furniture',
        position: { x: 450, y: 310 },
        rotation: 0,
        scale: 1,
        size: { width: 120, height: 60 },
        color: '#8B7355',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-kitchen',
        name: 'Kitchen Counter',
        category: 'Furniture',
        position: { x: 680, y: 150 },
        rotation: 0,
        scale: 1,
        size: { width: 220, height: 60 },
        color: '#C8C8C8',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-stool-1',
        name: 'Bar Stool 1',
        category: 'Furniture',
        position: { x: 600, y: 200 },
        rotation: 0,
        scale: 1,
        size: { width: 35, height: 35 },
        color: '#2A2A2A',
        shapeType: 'circle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-stool-2',
        name: 'Bar Stool 2',
        category: 'Furniture',
        position: { x: 670, y: 200 },
        rotation: 0,
        scale: 1,
        size: { width: 35, height: 35 },
        color: '#2A2A2A',
        shapeType: 'circle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
    ],
    
    shots: [],
    activeShotId: null,
    viewport: {
      offset: { x: 50, y: 50 },
      zoom: 1,
      minZoom: 0.1,
      maxZoom: 3,
    },
    showGrid: true,
    showRulers: false,
    showLineOfAction: true,
    show180Line: true,
    showFrustums: false,
    showMotionPaths: false,
    showMeasurements: false,
    snapToGrid: true,
    gridSize: 60,
    measurementUnit: 'meters',
    pixelsPerMeter: 10,
  };
};

// =============================================================================
// SCENE 2: Corporate Boardroom (INT. BOARDROOM - DAY)
// =============================================================================

export const createBoardroomScene = (): Scene2D => {
  const sceneWidth = 1000;
  const sceneHeight = 600;
  const pixelsPerMeter = 10;
  
  return {
    id: 'scene-boardroom',
    name: 'Scene 5: Boardroom Meeting',
    description: 'INT. CORPORATE BOARDROOM - DAY',
    location: 'Executive Boardroom',
    
    floorPlan: {
      id: 'floorplan-boardroom',
      name: 'Boardroom Layout',
      imageUrl: '',
      rooms: [],
      gridSize: 60,
      showGrid: false,
      gridOpacity: 0.2,
      scale: pixelsPerMeter,
      bounds: { x: 0, y: 0, width: sceneWidth, height: sceneHeight },
    },
    
    cameras: [
      {
        id: 'cam-a',
        name: 'Cam A',
        label: 'Cam A',
        position: { x: 150, y: 200 },
        rotation: 30,
        color: '#FFD700',
        shotType: 'WS',
        lens: '28mm',
        height: 'Eye Level',
        angle: 'Straight On',
        movement: 'Static',
        frustum: { nearDistance: 5, farDistance: 12, fov: 75 },
        showFrustum: true,
        frustumOpacity: 0.25,
        isSelected: false,
        isActive: true,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'cam-b',
        name: 'Cam B',
        label: 'Cam B',
        position: { x: 850, y: 250 },
        rotation: 160,
        color: '#4FC3F7',
        shotType: 'MCU',
        lens: '50mm',
        height: 'Eye Level',
        angle: 'Straight On',
        movement: 'Static',
        frustum: { nearDistance: 3, farDistance: 7, fov: 46 },
        showFrustum: true,
        frustumOpacity: 0.25,
        isSelected: false,
        isActive: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
    ],
    
    actors: [
      {
        id: 'actor-1',
        name: 'Executive 1',
        characterName: 'Sarah',
        position: { x: 400, y: 150 },
        rotation: 0,
        scale: 1,
        color: '#2D3748',
        pose: 'Sitting',
        facing: 'Right',
        showMovementPath: false,
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'actor-2',
        name: 'Executive 2',
        characterName: 'Marcus',
        position: { x: 500, y: 150 },
        rotation: 0,
        scale: 1,
        color: '#374151',
        pose: 'Sitting',
        facing: 'Left',
        showMovementPath: false,
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'actor-3',
        name: 'Executive 3',
        characterName: 'Diana',
        position: { x: 600, y: 150 },
        rotation: 0,
        scale: 1,
        color: '#1F2937',
        pose: 'Sitting',
        facing: 'Right',
        showMovementPath: false,
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'actor-4',
        name: 'Executive 4',
        characterName: 'James',
        position: { x: 500, y: 250 },
        rotation: 0,
        scale: 1,
        color: '#4A5568',
        pose: 'Standing',
        facing: 'Front',
        showMovementPath: false,
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
    ],
    
    props: [
      {
        id: 'prop-conference-table',
        name: 'Conference Table',
        category: 'Furniture',
        position: { x: 500, y: 150 },
        rotation: 0,
        scale: 1,
        size: { width: 400, height: 120 },
        color: '#8B4513',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-chair-1',
        name: 'Chair 1',
        category: 'Furniture',
        position: { x: 300, y: 150 },
        rotation: 0,
        scale: 1,
        size: { width: 50, height: 50 },
        color: '#2A2A2A',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-chair-2',
        name: 'Chair 2',
        category: 'Furniture',
        position: { x: 700, y: 150 },
        rotation: 0,
        scale: 1,
        size: { width: 50, height: 50 },
        color: '#2A2A2A',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-window-1',
        name: 'Window',
        category: 'Set Dressing',
        position: { x: 150, y: 100 },
        rotation: 0,
        scale: 1,
        size: { width: 200, height: 80 },
        color: '#87CEEB',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-whiteboard',
        name: 'Whiteboard',
        category: 'Lighting Equipment',
        position: { x: 900, y: 450 },
        rotation: 0,
        scale: 1,
        size: { width: 150, height: 100 },
        color: '#F5F5F5',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
    ],
    
    shots: [],
    activeShotId: null,
    viewport: {
      offset: { x: 30, y: 40 },
      zoom: 0.95,
      minZoom: 0.1,
      maxZoom: 3,
    },
    showGrid: true,
    showRulers: false,
    showLineOfAction: true,
    showFrustums: false,
    showMotionPaths: false,
    showMeasurements: false,
    show180Line: true,
    snapToGrid: true,
    gridSize: 60,
    measurementUnit: 'meters',
    pixelsPerMeter: 10,
  };
};

// =============================================================================
// SCENE 3: Master Bedroom (INT. MASTER BEDROOM - NIGHT)
// =============================================================================

export const createBedroomScene = (): Scene2D => {
  const sceneWidth = 800;
  const sceneHeight = 700;
  const pixelsPerMeter = 10;
  
  return {
    id: 'scene-bedroom',
    name: 'Scene 8: Bedroom Confrontation',
    description: 'INT. MASTER BEDROOM - NIGHT',
    location: 'Master Bedroom',
    
    floorPlan: {
      id: 'floorplan-bedroom',
      name: 'Bedroom Layout',
      imageUrl: '',
      rooms: [],
      gridSize: 60,
      showGrid: false,
      gridOpacity: 0.2,
      scale: pixelsPerMeter,
      bounds: { x: 0, y: 0, width: sceneWidth, height: sceneHeight },
    },
    
    cameras: [
      {
        id: 'cam-a',
        name: 'Cam A',
        label: 'Cam A',
        position: { x: 100, y: 300 },
        rotation: 15,
        color: '#FFD700',
        shotType: 'WS',
        lens: '35mm',
        height: 'Eye Level',
        angle: 'Straight On',
        movement: 'Static',
        frustum: { nearDistance: 4, farDistance: 9, fov: 63 },
        showFrustum: true,
        frustumOpacity: 0.25,
        isSelected: false,
        isActive: true,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'cam-b',
        name: 'Cam B',
        label: 'Cam B',
        position: { x: 750, y: 350 },
        rotation: 170,
        color: '#4FC3F7',
        shotType: 'CU',
        lens: '85mm',
        height: 'Eye Level',
        angle: 'Straight On',
        movement: 'Static',
        frustum: { nearDistance: 2, farDistance: 5, fov: 28 },
        showFrustum: true,
        frustumOpacity: 0.25,
        isSelected: false,
        isActive: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
    ],
    
    actors: [
      {
        id: 'actor-1',
        name: 'Character 1',
        characterName: 'Jessica',
        position: { x: 300, y: 250 },
        rotation: 0,
        scale: 1,
        color: '#2D3748',
        pose: 'Sitting',
        facing: 'Right',
        showMovementPath: false,
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'actor-2',
        name: 'Character 2',
        characterName: 'Michael',
        position: { x: 500, y: 300 },
        rotation: 0,
        scale: 1,
        color: '#374151',
        pose: 'Standing',
        facing: 'Left',
        showMovementPath: false,
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
    ],
    
    props: [
      {
        id: 'prop-bed',
        name: 'Bed',
        category: 'Furniture',
        position: { x: 400, y: 200 },
        rotation: 0,
        scale: 1,
        size: { width: 300, height: 180 },
        color: '#E8D4B8',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-nightstand',
        name: 'Night Stand',
        category: 'Furniture',
        position: { x: 600, y: 120 },
        rotation: 0,
        scale: 1,
        size: { width: 60, height: 60 },
        color: '#8B7355',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-lamp',
        name: 'Lamp',
        category: 'Hand Props',
        position: { x: 630, y: 100 },
        rotation: 0,
        scale: 1,
        size: { width: 20, height: 40 },
        color: '#FFD700',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 1,
      },
      {
        id: 'prop-wardrobe',
        name: 'Wardrobe',
        category: 'Furniture',
        position: { x: 100, y: 500 },
        rotation: 0,
        scale: 1,
        size: { width: 120, height: 100 },
        color: '#5D4E37',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
    ],
    
    shots: [],
    activeShotId: null,
    viewport: {
      offset: { x: 40, y: 40 },
      zoom: 1,
      minZoom: 0.1,
      maxZoom: 3,
    },
    showGrid: true,
    showRulers: false,
    showLineOfAction: true,
    showFrustums: false,
    showMotionPaths: false,
    showMeasurements: false,
    show180Line: true,
    snapToGrid: true,
    gridSize: 60,
    measurementUnit: 'meters',
    pixelsPerMeter: 10,
  };
};

// =============================================================================
// SCENE 4: Kitchen & Dining (INT. KITCHEN - DAY)
// =============================================================================

export const createKitchenScene = (): Scene2D => {
  const sceneWidth = 950;
  const sceneHeight: number = 650;
  const pixelsPerMeter = 10;
  
  return {
    id: 'scene-kitchen',
    name: 'Scene 3: Kitchen Confrontation',
    description: 'INT. KITCHEN & DINING - DAY',
    location: 'Kitchen & Dining Area',
    
    floorPlan: {
      id: 'floorplan-kitchen',
      name: 'Kitchen Layout',
      imageUrl: '',
      rooms: [],
      gridSize: 60,
      showGrid: false,
      gridOpacity: 0.2,
      scale: pixelsPerMeter,
      bounds: { x: 0, y: 0, width: sceneWidth, height: sceneHeight },
    },
    
    cameras: [
      {
        id: 'cam-a',
        name: 'Cam A',
        label: 'Cam A',
        position: { x: 150, y: 250 },
        rotation: 25,
        color: '#FFD700',
        shotType: 'WS',
        lens: '24mm',
        height: 'Eye Level',
        angle: 'Straight On',
        movement: 'Static',
        frustum: { nearDistance: 5, farDistance: 11, fov: 84 },
        showFrustum: true,
        frustumOpacity: 0.25,
        isSelected: false,
        isActive: true,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'cam-b',
        name: 'Cam B',
        label: 'Cam B',
        position: { x: 850, y: 400 },
        rotation: 165,
        color: '#4FC3F7',
        shotType: 'MS',
        lens: '35mm',
        height: 'Eye Level',
        angle: 'Straight On',
        movement: 'Static',
        frustum: { nearDistance: 3, farDistance: 8, fov: 63 },
        showFrustum: true,
        frustumOpacity: 0.25,
        isSelected: false,
        isActive: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'cam-c',
        name: 'Cam C',
        label: 'Cam C',
        position: { x: 500, y: 550 },
        rotation: -45,
        color: '#81C784',
        shotType: 'CU',
        lens: '50mm',
        height: 'Eye Level',
        angle: 'Straight On',
        movement: 'Static',
        frustum: { nearDistance: 2, farDistance: 5, fov: 46 },
        showFrustum: true,
        frustumOpacity: 0.25,
        isSelected: false,
        isActive: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
    ],
    
    actors: [
      {
        id: 'actor-1',
        name: 'Character 1',
        characterName: 'Emma',
        position: { x: 400, y: 300 },
        rotation: 0,
        scale: 1,
        color: '#2D3748',
        pose: 'Standing',
        facing: 'Right',
        showMovementPath: false,
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'actor-2',
        name: 'Character 2',
        characterName: 'David',
        position: { x: 600, y: 320 },
        rotation: 0,
        scale: 1,
        color: '#374151',
        pose: 'Standing',
        facing: 'Left',
        showMovementPath: false,
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
    ],
    
    props: [
      {
        id: 'prop-kitchen-counter-1',
        name: 'Counter 1',
        category: 'Furniture',
        position: { x: 200, y: 150 },
        rotation: 0,
        scale: 1,
        size: { width: 250, height: 70 },
        color: '#C8C8C8',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-kitchen-island',
        name: 'Island',
        category: 'Furniture',
        position: { x: 500, y: 280 },
        rotation: 0,
        scale: 1,
        size: { width: 180, height: 100 },
        color: '#E8E8E8',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-dining-table',
        name: 'Dining Table',
        category: 'Furniture',
        position: { x: 650, y: 180 },
        rotation: 0,
        scale: 1,
        size: { width: 200, height: 120 },
        color: '#8B4513',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-chairs',
        name: 'Dining Chairs',
        category: 'Furniture',
        position: { x: 600, y: 180 },
        rotation: 0,
        scale: 1,
        size: { width: 45, height: 45 },
        color: '#A0522D',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-stove',
        name: 'Stove',
        category: 'Lighting Equipment',
        position: { x: 250, y: 100 },
        rotation: 0,
        scale: 1,
        size: { width: 80, height: 80 },
        color: '#3A3A3A',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
    ],
    
    shots: [],
    activeShotId: null,
    viewport: {
      offset: { x: 30, y: 35 },
      zoom: 0.95,
      minZoom: 0.1,
      maxZoom: 3,
    },
    showGrid: true,
    showRulers: false,
    showLineOfAction: true,
    showFrustums: false,
    showMotionPaths: false,
    showMeasurements: false,
    show180Line: true,
    snapToGrid: true,
    gridSize: 60,
    measurementUnit: 'meters',
    pixelsPerMeter: 10,
  };
};

// =============================================================================
// SCENE 5: Industrial Warehouse (INT. WAREHOUSE - DAY)
// =============================================================================

export const createWarehouseScene = (): Scene2D => {
  const sceneWidth = 1200;
  const sceneHeight = 800;
  const pixelsPerMeter = 10;
  
  return {
    id: 'scene-warehouse',
    name: 'Scene 2: Warehouse Chase',
    description: 'INT. INDUSTRIAL WAREHOUSE - DAY',
    location: 'Abandoned Warehouse',
    
    floorPlan: {
      id: 'floorplan-warehouse',
      name: 'Warehouse Layout',
      imageUrl: '',
      rooms: [],
      gridSize: 80,
      showGrid: false,
      gridOpacity: 0.2,
      scale: pixelsPerMeter,
      bounds: { x: 0, y: 0, width: sceneWidth, height: sceneHeight },
    },
    
    cameras: [
      {
        id: 'cam-a',
        name: 'Cam A',
        label: 'Cam A',
        position: { x: 150, y: 300 },
        rotation: 20,
        color: '#FFD700',
        shotType: 'WS',
        lens: '21mm',
        height: 'Eye Level',
        angle: 'Straight On',
        movement: 'Dolly In',
        frustum: { nearDistance: 6, farDistance: 14, fov: 92 },
        showFrustum: true,
        frustumOpacity: 0.25,
        isSelected: false,
        isActive: true,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'cam-b',
        name: 'Cam B',
        label: 'Cam B',
        position: { x: 1050, y: 400 },
        rotation: 175,
        color: '#4FC3F7',
        shotType: 'WS',
        lens: '24mm',
        height: 'Eye Level',
        angle: 'Straight On',
        movement: 'Static',
        frustum: { nearDistance: 5, farDistance: 12, fov: 84 },
        showFrustum: true,
        frustumOpacity: 0.25,
        isSelected: false,
        isActive: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
    ],
    
    actors: [
      {
        id: 'actor-1',
        name: 'Actor 1',
        characterName: 'Runner',
        position: { x: 400, y: 350 },
        rotation: 0,
        scale: 1.1,
        color: '#2D3748',
        pose: 'Running',
        facing: 'Right',
        showMovementPath: true,
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'actor-2',
        name: 'Actor 2',
        characterName: 'Pursuer',
        position: { x: 300, y: 380 },
        rotation: 0,
        scale: 1,
        color: '#374151',
        pose: 'Running',
        facing: 'Right',
        showMovementPath: true,
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
    ],
    
    props: [
      {
        id: 'prop-crate-1',
        name: 'Cargo Crate 1',
        category: 'Hand Props',
        position: { x: 500, y: 250 },
        rotation: 0,
        scale: 1,
        size: { width: 120, height: 120 },
        color: '#8B6F47',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-crate-2',
        name: 'Cargo Crate 2',
        category: 'Hand Props',
        position: { x: 700, y: 200 },
        rotation: 0,
        scale: 1,
        size: { width: 140, height: 140 },
        color: '#7A5C3A',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-crate-3',
        name: 'Cargo Crate 3',
        category: 'Hand Props',
        position: { x: 850, y: 350 },
        rotation: 15,
        scale: 1,
        size: { width: 100, height: 100 },
        color: '#8B6F47',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-barrel-1',
        name: 'Barrel',
        category: 'Hand Props',
        position: { x: 600, y: 450 },
        rotation: 0,
        scale: 1,
        size: { width: 50, height: 70 },
        color: '#4A4A4A',
        shapeType: 'circle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-window',
        name: 'High Window',
        category: 'Set Dressing',
        position: { x: 300, y: 50 },
        rotation: 0,
        scale: 1,
        size: { width: 200, height: 60 },
        color: '#87CEEB',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
    ],
    
    shots: [],
    activeShotId: null,
    viewport: {
      offset: { x: 20, y: 30 },
      zoom: 0.8,
      minZoom: 0.1,
      maxZoom: 3,
    },
    showGrid: true,
    showRulers: false,
    showLineOfAction: true,
    showFrustums: false,
    showMotionPaths: false,
    showMeasurements: false,
    show180Line: true,
    snapToGrid: true,
    gridSize: 60,
    measurementUnit: 'meters',
    pixelsPerMeter: 10,
  };
};

// =============================================================================
// SCENE 6: Restaurant/Bar (INT. RESTAURANT - NIGHT)
// =============================================================================

export const createRestaurantScene = (): Scene2D => {
  const sceneWidth = 1000;
  const sceneHeight = 700;
  const pixelsPerMeter = 10;
  
  return {
    id: 'scene-restaurant',
    name: 'Scene 7: Restaurant Meeting',
    description: 'INT. UPSCALE RESTAURANT - NIGHT',
    location: 'Fine Dining Restaurant',
    
    floorPlan: {
      id: 'floorplan-restaurant',
      name: 'Restaurant Layout',
      imageUrl: '',
      rooms: [],
      gridSize: 60,
      showGrid: false,
      gridOpacity: 0.2,
      scale: pixelsPerMeter,
      bounds: { x: 0, y: 0, width: sceneWidth, height: sceneHeight },
    },
    
    cameras: [
      {
        id: 'cam-a',
        name: 'Cam A',
        label: 'Cam A',
        position: { x: 100, y: 250 },
        rotation: 20,
        color: '#FFD700',
        shotType: 'WS',
        lens: '35mm',
        height: 'Eye Level',
        angle: 'Straight On',
        movement: 'Static',
        frustum: { nearDistance: 4, farDistance: 9, fov: 63 },
        showFrustum: true,
        frustumOpacity: 0.25,
        isSelected: false,
        isActive: true,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'cam-b',
        name: 'Cam B',
        label: 'Cam B',
        position: { x: 900, y: 300 },
        rotation: 170,
        color: '#4FC3F7',
        shotType: 'CU',
        lens: '50mm',
        height: 'Eye Level',
        angle: '3/4 Front',
        movement: 'Static',
        frustum: { nearDistance: 2, farDistance: 6, fov: 46 },
        showFrustum: true,
        frustumOpacity: 0.25,
        isSelected: false,
        isActive: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
    ],
    
    actors: [
      {
        id: 'actor-1',
        name: 'Diner 1',
        characterName: 'Client',
        position: { x: 400, y: 250 },
        rotation: 0,
        scale: 1,
        color: '#2D3748',
        pose: 'Sitting',
        facing: 'Right',
        showMovementPath: false,
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'actor-2',
        name: 'Diner 2',
        characterName: 'Agent',
        position: { x: 500, y: 250 },
        rotation: 0,
        scale: 1,
        color: '#374151',
        pose: 'Sitting',
        facing: 'Left',
        showMovementPath: false,
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'actor-3',
        name: 'Waiter',
        characterName: 'Service',
        position: { x: 600, y: 200 },
        rotation: 0,
        scale: 1,
        color: '#1F2937',
        pose: 'Standing',
        facing: 'Front',
        showMovementPath: false,
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
    ],
    
    props: [
      {
        id: 'prop-table-1',
        name: 'Dining Table',
        category: 'Furniture',
        position: { x: 450, y: 250 },
        rotation: 0,
        scale: 1,
        size: { width: 150, height: 100 },
        color: '#8B4513',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-table-2',
        name: 'Bar Table',
        category: 'Furniture',
        position: { x: 750, y: 150 },
        rotation: 0,
        scale: 1,
        size: { width: 80, height: 80 },
        color: '#654321',
        shapeType: 'circle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-bar',
        name: 'Bar Counter',
        category: 'Furniture',
        position: { x: 800, y: 500 },
        rotation: 0,
        scale: 1,
        size: { width: 300, height: 60 },
        color: '#3A2A1A',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-plant',
        name: 'Plant',
        category: 'Set Dressing',
        position: { x: 200, y: 150 },
        rotation: 0,
        scale: 1,
        size: { width: 50, height: 80 },
        color: '#228B22',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-painting',
        name: 'Wall Painting',
        category: 'Set Dressing',
        position: { x: 950, y: 100 },
        rotation: 0,
        scale: 1,
        size: { width: 100, height: 120 },
        color: '#DAA520',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
    ],
    
    shots: [],
    activeShotId: null,
    viewport: {
      offset: { x: 30, y: 40 },
      zoom: 0.95,
      minZoom: 0.1,
      maxZoom: 3,
    },
    showGrid: true,
    showRulers: false,
    showLineOfAction: true,
    showFrustums: false,
    showMotionPaths: false,
    showMeasurements: false,
    show180Line: true,
    snapToGrid: true,
    gridSize: 60,
    measurementUnit: 'meters',
    pixelsPerMeter: 10,
  };
};

// =============================================================================
// SCENE 7: Hospital Room (INT. HOSPITAL ROOM - DAY)
// =============================================================================

export const createHospitalScene = (): Scene2D => {
  const sceneWidth = 750;
  const sceneHeight = 600;
  const pixelsPerMeter = 10;
  
  return {
    id: 'scene-hospital',
    name: 'Scene 9: Hospital Visit',
    description: 'INT. HOSPITAL ROOM - DAY',
    location: 'Private Hospital Room',
    
    floorPlan: {
      id: 'floorplan-hospital',
      name: 'Hospital Room Layout',
      imageUrl: '',
      rooms: [],
      gridSize: 60,
      showGrid: false,
      gridOpacity: 0.2,
      scale: pixelsPerMeter,
      bounds: { x: 0, y: 0, width: sceneWidth, height: sceneHeight },
    },
    
    cameras: [
      {
        id: 'cam-a',
        name: 'Cam A',
        label: 'Cam A',
        position: { x: 80, y: 250 },
        rotation: 15,
        color: '#FFD700',
        shotType: 'WS',
        lens: '35mm',
        height: 'Eye Level',
        angle: 'Straight On',
        movement: 'Static',
        frustum: { nearDistance: 3, farDistance: 8, fov: 63 },
        showFrustum: true,
        frustumOpacity: 0.25,
        isSelected: false,
        isActive: true,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'cam-b',
        name: 'Cam B',
        label: 'Cam B',
        position: { x: 650, y: 300 },
        rotation: 170,
        color: '#4FC3F7',
        shotType: 'CU',
        lens: '50mm',
        height: 'Eye Level',
        angle: 'Straight On',
        movement: 'Static',
        frustum: { nearDistance: 2, farDistance: 5, fov: 46 },
        showFrustum: true,
        frustumOpacity: 0.25,
        isSelected: false,
        isActive: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
    ],
    
    actors: [
      {
        id: 'actor-1',
        name: 'Patient',
        characterName: 'John',
        position: { x: 350, y: 200 },
        rotation: 0,
        scale: 0.9,
        color: '#2D3748',
        pose: 'Lying',
        facing: 'Front',
        showMovementPath: false,
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'actor-2',
        name: 'Visitor',
        characterName: 'Sarah',
        position: { x: 400, y: 350 },
        rotation: 0,
        scale: 1,
        color: '#374151',
        pose: 'Sitting',
        facing: 'Left',
        showMovementPath: false,
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
    ],
    
    props: [
      {
        id: 'prop-hospital-bed',
        name: 'Hospital Bed',
        category: 'Lighting Equipment',
        position: { x: 350, y: 150 },
        rotation: 0,
        scale: 1,
        size: { width: 200, height: 120 },
        color: '#E8E8E8',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-iv-stand',
        name: 'IV Stand',
        category: 'Lighting Equipment',
        position: { x: 450, y: 80 },
        rotation: 0,
        scale: 1,
        size: { width: 30, height: 80 },
        color: '#4A5568',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-monitor',
        name: 'Heart Monitor',
        category: 'Lighting Equipment',
        position: { x: 520, y: 100 },
        rotation: 0,
        scale: 1,
        size: { width: 60, height: 50 },
        color: '#2A2A2A',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-chair',
        name: 'Visitor Chair',
        category: 'Furniture',
        position: { x: 400, y: 400 },
        rotation: 0,
        scale: 1,
        size: { width: 60, height: 60 },
        color: '#808080',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
      {
        id: 'prop-window',
        name: 'Window',
        category: 'Set Dressing',
        position: { x: 150, y: 100 },
        rotation: 0,
        scale: 1,
        size: { width: 120, height: 100 },
        color: '#87CEEB',
        shapeType: 'rectangle',
        isSelected: false,
        locked: false,
        visible: true,
        zIndex: 0,
      },
    ],
    
    shots: [],
    activeShotId: null,
    viewport: {
      offset: { x: 50, y: 50 },
      zoom: 1.05,
      minZoom: 0.1,
      maxZoom: 3,
    },
    showGrid: true,
    showRulers: false,
    showLineOfAction: true,
    showFrustums: false,
    showMotionPaths: false,
    showMeasurements: false,
    show180Line: true,
    snapToGrid: true,
    gridSize: 60,
    measurementUnit: 'meters',
    pixelsPerMeter: 10,
  };
};

// =============================================================================
// All Scenes Export
// =============================================================================

export const DEMO_SCENES = [
  createSafehouseScene,
  createBoardroomScene,
  createBedroomScene,
  createKitchenScene,
  createWarehouseScene,
  createRestaurantScene,
  createHospitalScene,
];

export const SCENE_TEMPLATES: Array<{
  id: string;
  name: string;
  description: string;
  create: () => Scene2D;
}> = [
  {
    id: 'safehouse',
    name: 'The Safehouse',
    description: 'Living room - intimate indoor space',
    create: createSafehouseScene,
  },
  {
    id: 'boardroom',
    name: 'Corporate Boardroom',
    description: 'Conference room - formal meeting space',
    create: createBoardroomScene,
  },
  {
    id: 'bedroom',
    name: 'Master Bedroom',
    description: 'Bedroom - private intimate space',
    create: createBedroomScene,
  },
  {
    id: 'kitchen',
    name: 'Kitchen & Dining',
    description: 'Kitchen - domestic cooking & dining space',
    create: createKitchenScene,
  },
  {
    id: 'warehouse',
    name: 'Industrial Warehouse',
    description: 'Warehouse - large open industrial space',
    create: createWarehouseScene,
  },
  {
    id: 'restaurant',
    name: 'Restaurant/Bar',
    description: 'Restaurant - social dining space',
    create: createRestaurantScene,
  },
  {
    id: 'hospital',
    name: 'Hospital Room',
    description: 'Hospital - clinical medical space',
    create: createHospitalScene,
  },
];
