import Foundation
import Testing
@testable import SceneDocument

/// The Swift validator, held to the verdicts the web studio reaches.
///
/// Every case comes from `Fixtures/documents.json`, generated by
/// `src/services/studioDocument.fixtures.test.ts`. A native app that accepts
/// what the browser refuses will open half a scene over someone's work; one that
/// refuses what the browser writes will not open their own files. Either way the
/// promise that both editions share one document is broken, so this is the test
/// that has to stay green for the rest of the plan to mean anything.
private struct Fixture: Decodable {
    struct Case: Decodable {
        let name: String
        let accepted: Bool
        let document: JSONValue
    }
    let source: String
    let cases: [Case]
}

private let fixture: Fixture = {
    guard let url = Bundle.module.url(forResource: "documents", withExtension: "json", subdirectory: "Fixtures") else {
        fatalError("documents.json is missing. Generate it with UPDATE_FIXTURES=1 npm test -- studioDocument.fixtures")
    }
    // swiftlint:disable:next force_try
    return try! JSONDecoder().decode(Fixture.self, from: Data(contentsOf: url))
}()

@Test("every document gets the same verdict as in the browser")
func verdictsMatch() {
    for entry in fixture.cases {
        var accepted = true
        var failure: (any Error)?
        do {
            _ = try parseStudioDocument(entry.document)
        } catch let thrown {
            accepted = false
            failure = thrown
        }
        if accepted != entry.accepted {
            Issue.record(
                accepted
                    ? "accepted \"\(entry.name)\", which the browser refuses"
                    : "refused \"\(entry.name)\", which the browser accepts: \(failure.map { String(describing: $0) } ?? "")"
            )
        }
    }
}

@Test("there are cases on both sides of the line")
func fixtureIsNotDegenerate() {
    // A fixture that had lost its refusals would make the test above pass for
    // the wrong reason.
    #expect(fixture.cases.count(where: { $0.accepted }) > 10)
    #expect(fixture.cases.count(where: { !$0.accepted }) > 10)
}

@Test("a valid document keeps every field, including ones this version invented no meaning for")
func carriesUnknownFields() throws {
    let entry = try #require(fixture.cases.first { $0.name == "fields from a later version" })
    let document = try parseStudioDocument(entry.document)

    // The storyboard is not modelled here at all, and must survive anyway.
    #expect(document.json["storyboard"]?["title"]?.stringValue == "Holy Crust · 20 sekunder")
    #expect(document.json["somethingLater"]?["ok"]?.boolValue == true)

    // And through a real save: encode, decode, validate again, unchanged.
    let data = try JSONEncoder().encode(document.json)
    let reopened = try parseStudioDocument(data: data)
    #expect(reopened.json == document.json)
    #expect(reopened == document)
}

@Test("what it reads out of a document is what the document says")
func readsTheScene() throws {
    let entry = try #require(fixture.cases.first { $0.name == "a place with its switches and whose place it is" })
    let document = try parseStudioDocument(entry.document)

    #expect(document.id == "doc-1")
    #expect(document.cameras.count == 1)
    #expect(document.cameras[0].radius == 4)
    #expect(document.cameras[0].target.y == 1.4)
    #expect(document.room?.kind == .pizzeria)
    #expect(document.room?.furnishings == true)
    #expect(document.room?.brandName == "Holy Crust")
    #expect(document.cameraSettings.aperture == 2.8)
    #expect(document.cameraSettings.shutter == "1/125")
    #expect(abs(document.cameraSettings.shutterSeconds - 1.0 / 125.0) < 1e-15)
}

@Test("a shutter reads as the time it names")
func shutterSeconds() throws {
    let cases: [(String, Double)] = [("1/125", 1.0 / 125), ("1/8000", 1.0 / 8000), ("2", 2), ("0.5", 0.5)]
    for (written, seconds) in cases {
        let entry = try #require(fixture.cases.first { $0.name == "the shutter \(written)" })
        let document = try parseStudioDocument(entry.document)
        #expect(abs(document.cameraSettings.shutterSeconds - seconds) < 1e-15, "\(written)")
    }
}

@Test("a number that is not a number is refused, which JSON cannot even carry")
func refusesNonFinite() {
    // The one rule the shared fixture cannot express: JSON has no Infinity, so
    // it has to be asserted against a tree built in memory. A document handed
    // over from another part of a running app can still contain one.
    let broken = JSONValue.object([
        "id": .string("doc"), "name": .string("Oppsett"),
        "createdAt": .string("now"), "updatedAt": .string("now"),
        "cameras": .array([.object([
            "id": .string("cam"), "alpha": .number(0), "beta": .number(1.2),
            "radius": .number(.infinity),
            "target": .object(["x": .number(0), "y": .number(1.4), "z": .number(0)]),
            "fov": .number(0.8),
        ])]),
        "lights": .array([]), "actors": .array([]), "props": .array([]), "layers": .array([]),
        "cameraSettings": .object([
            "aperture": .number(2.8), "iso": .number(100), "focalLength": .number(50),
            "shutter": .string("1/125"), "nd": .number(0),
        ]),
    ])
    #expect(throws: DocumentError.notFinite("cameras[0].radius")) { try parseStudioDocument(broken) }
}

@Test("the error says which field was wrong")
func errorsName() throws {
    // The web version throws one sentence, which is all a file picker needed. On
    // a device the photographer is standing in the room with the file, so the
    // failed state has to say something they can act on.
    let entry = try #require(fixture.cases.first { $0.name == "a room this studio does not build" })
    #expect(throws: DocumentError.unknownValue("environment.room.type", "spaceship")) {
        try parseStudioDocument(entry.document)
    }
    #expect(DocumentError.unknownValue("environment.room.type", "spaceship").description
        == "environment.room.type does not know \"spaceship\"")

    let noCamera = try #require(fixture.cases.first { $0.name == "a scene with no camera to shoot it from" })
    #expect(throws: DocumentError.empty("cameras")) { try parseStudioDocument(noCamera.document) }
}

@Test("every room this studio builds, and no others")
func roomKinds() {
    #expect(StudioDocument.RoomKind.allCases.map(\.rawValue)
        == ["none", "industrial", "kitchen", "hospital", "pizzeria"])
    #expect(StudioDocument.TrackChannel.allCases.map(\.rawValue)
        == ["position", "rotation", "intensity", "color", "target"])
}
