/**
 * Actor Mesh Component
 * 
 * Renders virtual actor meshes generated by Anny in the 3D scene.
 * Integrates with React Three Fiber for efficient rendering.
 * 
 * Features:
 * - Dynamic geometry from Anny service
 * - PBR skin materials
 * - Transform controls (position, rotation, scale)
 * - Visibility toggle
 * - Realistic human silhouette placeholder
 */

import React, { useEffect, useRef, useMemo } from 'react';
import { logger } from '../../core/services/logger';

const log = logger.module('ActorMesh');
import { SceneNode } from '../../core/models/scene';

// Dynamic THREE import (same pattern as Stage3D)
let THREE: any = null;
try {
  THREE = require('three');
} catch {
  log.warn('THREE.js not available in ActorMesh');
}

interface ActorMeshProps {
  node: SceneNode;
}

/**
 * Create a realistic human silhouette mesh
 * Used as a placeholder when Anny service hasn't generated the mesh yet
 */
function createHumanSilhouette(height: number = 1.7, skinTone: string = '#f4c2a0'): {
  geometry: THREE.BufferGeometry;
  material: THREE.Material;
} {
  if (!THREE) {
    return { geometry: null, material: null };
  }

  const group = new THREE.Group();
  
  // Proportions based on average adult human (8 heads tall)
  const headHeight = height / 8;
  const torsoHeight = height * 0.35;
  const legHeight = height * 0.47;
  const armLength = height * 0.38;
  
  // Create merged geometry from body parts
  const geometries: THREE.BufferGeometry[] = [];

  // Head (sphere)
  const headGeom = new THREE.SphereGeometry(headHeight * 0.5, 16, 12);
  headGeom.translate(0, height - headHeight * 0.5, 0);
  geometries.push(headGeom);

  // Neck (cylinder)
  const neckGeom = new THREE.CylinderGeometry(
    headHeight * 0.2,
    headHeight * 0.25,
    headHeight * 0.3,
    8
  );
  neckGeom.translate(0, height - headHeight - headHeight * 0.15, 0);
  geometries.push(neckGeom);

  // Torso (tapered cylinder)
  const shoulderWidth = headHeight * 1.8;
  const hipWidth = headHeight * 1.2;
  const torsoGeom = new THREE.CylinderGeometry(
    shoulderWidth / 2,
    hipWidth / 2,
    torsoHeight,
    12
  );
  torsoGeom.translate(0, height - headHeight - headHeight * 0.3 - torsoHeight / 2, 0);
  geometries.push(torsoGeom);

  // Left arm (capsule-like)
  const armRadius = headHeight * 0.15;
  const upperArmGeom = new THREE.CylinderGeometry(
    armRadius * 1.1,
    armRadius * 0.9,
    armLength * 0.5,
    8
  );
  upperArmGeom.rotateZ(Math.PI * 0.1); // Slight angle out
  upperArmGeom.translate(
    -shoulderWidth / 2 - armRadius,
    height - headHeight - headHeight * 0.35 - armLength * 0.25,
    0
  );
  geometries.push(upperArmGeom);

  const lowerArmGeom = new THREE.CylinderGeometry(
    armRadius * 0.9,
    armRadius * 0.7,
    armLength * 0.45,
    8
  );
  lowerArmGeom.translate(
    -shoulderWidth / 2 - armRadius * 1.5,
    height - headHeight - headHeight * 0.35 - armLength * 0.7,
    0
  );
  geometries.push(lowerArmGeom);

  // Right arm (mirror)
  const upperArmGeomR = new THREE.CylinderGeometry(
    armRadius * 1.1,
    armRadius * 0.9,
    armLength * 0.5,
    8
  );
  upperArmGeomR.rotateZ(-Math.PI * 0.1);
  upperArmGeomR.translate(
    shoulderWidth / 2 + armRadius,
    height - headHeight - headHeight * 0.35 - armLength * 0.25,
    0
  );
  geometries.push(upperArmGeomR);

  const lowerArmGeomR = new THREE.CylinderGeometry(
    armRadius * 0.9,
    armRadius * 0.7,
    armLength * 0.45,
    8
  );
  lowerArmGeomR.translate(
    shoulderWidth / 2 + armRadius * 1.5,
    height - headHeight - headHeight * 0.35 - armLength * 0.7,
    0
  );
  geometries.push(lowerArmGeomR);

  // Pelvis/Hips (sphere)
  const pelvisGeom = new THREE.SphereGeometry(hipWidth / 2, 12, 8);
  pelvisGeom.scale(1, 0.6, 0.8);
  pelvisGeom.translate(0, legHeight + headHeight * 0.2, 0);
  geometries.push(pelvisGeom);

  // Left leg
  const legRadius = headHeight * 0.2;
  const upperLegGeom = new THREE.CylinderGeometry(
    legRadius * 1.3,
    legRadius * 1.0,
    legHeight * 0.5,
    8
  );
  upperLegGeom.translate(-hipWidth / 3, legHeight * 0.75, 0);
  geometries.push(upperLegGeom);

  const lowerLegGeom = new THREE.CylinderGeometry(
    legRadius * 1.0,
    legRadius * 0.7,
    legHeight * 0.5,
    8
  );
  lowerLegGeom.translate(-hipWidth / 3, legHeight * 0.25, 0);
  geometries.push(lowerLegGeom);

  // Right leg (mirror)
  const upperLegGeomR = new THREE.CylinderGeometry(
    legRadius * 1.3,
    legRadius * 1.0,
    legHeight * 0.5,
    8
  );
  upperLegGeomR.translate(hipWidth / 3, legHeight * 0.75, 0);
  geometries.push(upperLegGeomR);

  const lowerLegGeomR = new THREE.CylinderGeometry(
    legRadius * 1.0,
    legRadius * 0.7,
    legHeight * 0.5,
    8
  );
  lowerLegGeomR.translate(hipWidth / 3, legHeight * 0.25, 0);
  geometries.push(lowerLegGeomR);

  // Feet (boxes)
  const footGeom = new THREE.BoxGeometry(legRadius * 1.4, legRadius * 0.5, legRadius * 2.5);
  footGeom.translate(-hipWidth / 3, legRadius * 0.25, legRadius * 0.3);
  geometries.push(footGeom);

  const footGeomR = new THREE.BoxGeometry(legRadius * 1.4, legRadius * 0.5, legRadius * 2.5);
  footGeomR.translate(hipWidth / 3, legRadius * 0.25, legRadius * 0.3);
  geometries.push(footGeomR);

  // Merge all geometries
  const mergedGeometry = THREE.BufferGeometryUtils
    ? THREE.BufferGeometryUtils.mergeGeometries(geometries)
    : mergeGeometries(geometries);

  // Create PBR skin material
  const material = new THREE.MeshStandardMaterial({
    color: new THREE.Color(skinTone),
    roughness: 0.6,
    metalness: 0.0,
    side: THREE.DoubleSide,
  });

  return {
    geometry: mergedGeometry || new THREE.BufferGeometry(),
    material,
  };
}

// Fallback merge function if BufferGeometryUtils not available
function mergeGeometries(geometries: THREE.BufferGeometry[]): THREE.BufferGeometry {
  if (!THREE) return null;
  
  // Simple merge - just use the first geometry as a fallback
  // In production, BufferGeometryUtils should be available
  const merged = new THREE.BufferGeometry();
  
  let totalVertices = 0;
  let totalIndices = 0;
  
  for (const geom of geometries) {
    const positions = geom.getAttribute('position');
    const indices = geom.getIndex();
    totalVertices += positions ? positions.count : 0;
    totalIndices += indices ? indices.count : 0;
  }
  
  const positions = new Float32Array(totalVertices * 3);
  const normals = new Float32Array(totalVertices * 3);
  const indices = new Uint32Array(totalIndices);
  
  let vertexOffset = 0;
  let indexOffset = 0;
  let indexVertexOffset = 0;
  
  for (const geom of geometries) {
    const posAttr = geom.getAttribute('position');
    const normAttr = geom.getAttribute('normal');
    const indexAttr = geom.getIndex();
    
    if (posAttr) {
      for (let i = 0; i < posAttr.count * 3; i++) {
        positions[vertexOffset + i] = posAttr.array[i];
      }
      if (normAttr) {
        for (let i = 0; i < normAttr.count * 3; i++) {
          normals[vertexOffset + i] = normAttr.array[i];
        }
      }
    }
    
    if (indexAttr) {
      for (let i = 0; i < indexAttr.count; i++) {
        indices[indexOffset + i] = indexAttr.array[i] + indexVertexOffset;
      }
      indexOffset += indexAttr.count;
    }
    
    if (posAttr) {
      indexVertexOffset += posAttr.count;
      vertexOffset += posAttr.count * 3;
    }
  }
  
  merged.setAttribute('position', new THREE.BufferAttribute(positions, 3));
  merged.setAttribute('normal', new THREE.BufferAttribute(normals, 3));
  merged.setIndex(new THREE.BufferAttribute(indices, 1));
  
  merged.computeVertexNormals();
  
  return merged;
}

/**
 * ActorMesh Component
 * Renders a virtual actor mesh in the scene
 */
export function ActorMesh({ node }: ActorMeshProps) {
  const meshRef = useRef<any>(null);

  // Extract geometry and material from userData or create placeholder
  const { geometry, material } = useMemo(() => {
    if (!node.userData || !THREE) {
      return { geometry: null, material: null };
    }

    const userData = node.userData as any;
    
    // If geometry and material are already created by Anny service, use them
    if (userData.geometry && userData.material) {
      return {
        geometry: userData.geometry,
        material: userData.material,
      };
    }

    // Create realistic human silhouette placeholder
    const actorParams = userData.actorParams || {};
    const height = actorParams.height 
      ? 1.5 + actorParams.height * 0.4 // Map 0-1 to 1.5-1.9m
      : 1.7;
    
    // Get skin tone from store or default
    const skinTone = userData.skinTone ||'#f4c2a0';

    return createHumanSilhouette(height, skinTone);
  }, [node.userData]);

  // Update mesh when node changes
  useEffect(() => {
    if (!meshRef.current || !geometry || !material) return;

    meshRef.current.geometry = geometry;
    meshRef.current.material = material;
  }, [geometry, material]);

  // Update transform when node changes
  useEffect(() => {
    if (!meshRef.current) return;

    const [x, y, z] = node.transform.position;
    meshRef.current.position.set(x, y, z);

    const [rx, ry, rz] = node.transform.rotation;
    meshRef.current.rotation.set(rx, ry, rz);

    const [sx, sy, sz] = node.transform.scale;
    meshRef.current.scale.set(sx, sy, sz);
  }, [node.transform]);

  // Update visibility when node changes
  useEffect(() => {
    if (!meshRef.current) return;
    meshRef.current.visible = node.visible;
  }, [node.visible]);

  if (!THREE || !geometry || !material) {
    return null;
  }

  return (
    <mesh
      ref={meshRef}
      position={node.transform.position}
      rotation={node.transform.rotation}
      scale={node.transform.scale}
      visible={node.visible}
      castShadow
      receiveShadow
    >
      <primitive object={geometry} attach="geometry" />
      <primitive object={material} attach="material" />
    </mesh>
  );
}

export default ActorMesh;
