import { describe, it, expect } from 'vitest';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  MAX_EXTENSION, solveTwoBoneIk, chainPole, normalize, reject, cross, length,
  type TwoBoneChain, type Vec3,
} from './limbIk';

/**
 * Where the elbow goes, written down for both languages.
 *
 * Two facts cost real debugging time in the web version and are easy to lose in
 * a port: a limb must not lock straight, and a solved limb must keep the bend
 * plane its clip gave it or the elbow flips behind the body. Both are in here as
 * cases rather than as prose.
 *
 *   UPDATE_FIXTURES=1 npm test -- limbIk.fixtures
 */

const FIXTURE = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../../../apple/VirtualstudioCore/Tests/LimbIKTests/Fixtures/limbIk.json',
);

const v = (x: number, y: number, z: number): Vec3 => ({ x, y, z });

/** An arm and a leg at roughly the bundled figures' proportions, in metres. */
const ARM: TwoBoneChain = { root: v(0.18, 1.42, 0), mid: v(0.2, 1.15, -0.02), end: v(0.22, 0.9, 0.04) };
const LEG: TwoBoneChain = { root: v(0.1, 0.92, 0), mid: v(0.1, 0.5, 0.03), end: v(0.1, 0.08, 0) };
/** A limb already straight: it has no bend plane of its own. */
const STRAIGHT: TwoBoneChain = { root: v(0, 1.4, 0), mid: v(0, 1.15, 0), end: v(0, 0.9, 0) };
/** Uneven segments, so `minReach` matters. */
const UNEVEN: TwoBoneChain = { root: v(0, 1, 0), mid: v(0, 0.6, 0), end: v(0, 0.5, 0) };

const CASES: { name: string; chain: TwoBoneChain; target: Vec3; pole?: Vec3 }[] = [
  { name: 'arm reaching forward', chain: ARM, target: v(0.35, 1.1, 0.4) },
  { name: 'arm reaching across the body', chain: ARM, target: v(-0.2, 1.2, 0.3) },
  { name: 'arm resting on a thigh, as the seated clip does', chain: ARM, target: v(0.22, 0.78, 0.22) },
  { name: 'arm with an explicit pole, elbow out', chain: ARM, target: v(0.3, 1.1, 0.3), pole: v(1, 0, 0) },
  { name: 'arm with an explicit pole, elbow down', chain: ARM, target: v(0.3, 1.1, 0.3), pole: v(0, -1, 0) },
  { name: 'arm reaching further than it can', chain: ARM, target: v(2, 1.4, 0) },
  { name: 'arm folded to the shoulder', chain: ARM, target: v(0.18, 1.42, 0.001) },
  { name: 'leg stepping forward', chain: LEG, target: v(0.1, 0.1, 0.45) },
  { name: 'leg sitting, foot on the floor', chain: LEG, target: v(0.12, 0.02, 0.3) },
  { name: 'leg reaching further than it can', chain: LEG, target: v(0.1, -2, 0) },
  { name: 'straight limb keeps a plane anyway', chain: STRAIGHT, target: v(0.2, 1.0, 0.1) },
  { name: 'straight limb with a pole along the limb', chain: STRAIGHT, target: v(0, 0.95, 0), pole: v(0, -1, 0) },
  { name: 'uneven segments, target too close', chain: UNEVEN, target: v(0, 0.98, 0) },
  { name: 'target on top of the root', chain: ARM, target: v(0.18, 1.42, 0) },
];

function build() {
  return {
    source: 'src/core/rendering/limbIk.ts',
    note: 'Generated by limbIk.fixtures.test.ts. Read by LimbIKTests in apple/VirtualstudioCore.',
    MAX_EXTENSION,
    chainPole: [ARM, LEG, STRAIGHT, UNEVEN].map((chain, index) => ({ chain: index, pole: chainPole(chain) })),
    vectors: [
      { a: v(3, 0, 4), b: v(0, 1, 0) },
      { a: v(0.3, -0.8, 0.5), b: v(1, 0, 0) },
      { a: v(0, 0, 0), b: v(0, 0, 1) },
    ].map(({ a, b }) => ({
      a, b, unit: normalize(a), lengthOfA: length(a),
      rejected: reject(a, normalize(b)), crossed: cross(a, b),
    })),
    solutions: CASES.map(({ name, chain, target, pole }) => ({
      name, chain, target, pole: pole ?? null,
      solution: solveTwoBoneIk(chain, target, pole),
    })),
  };
}

describe('where the elbow goes, for both editions', () => {
  it('matches the fixture the Swift suite reads', () => {
    const current = build();
    if (process.env.UPDATE_FIXTURES) {
      mkdirSync(dirname(FIXTURE), { recursive: true });
      writeFileSync(FIXTURE, `${JSON.stringify(current, null, 2)}\n`);
    }
    // Through JSON both ways: the fixture is a file, and -0 does not survive
    // being written to one.
    expect(JSON.parse(JSON.stringify(current))).toEqual(JSON.parse(readFileSync(FIXTURE, 'utf8')));
  });

  it('covers both a reachable target and one that is not', () => {
    const solutions = build().solutions;
    expect(solutions.some(s => s.solution.overextended)).toBe(true);
    expect(solutions.some(s => !s.solution.overextended)).toBe(true);
    // And no limb ever locks straight, whatever it was asked for.
    for (const { name, solution } of solutions) {
      expect(solution.bend, name).toBeLessThan(Math.PI);
    }
  });
});
