import { describe, it, expect } from 'vitest';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  INCIDENT_METER_CONSTANT_C, SCENE_INTENSITY_PER_CANDELA, DEFAULT_BEAM_ANGLE_DEG,
  REFERENCE_SHUTTER_SECONDS, MAX_SPOT_CONE_RAD,
  spotConeRadians, coneSolidAngle, fixtureCandela, isFlashFixture,
  flashLuminousExposureAt1m, flashEquivalentCandela, flashShutterCompensation, flashApertureAt,
  illuminanceAt, distanceForIlluminance, stopsBetween, evAtIso100, apertureForIlluminance,
  sceneIntensityFromCandela, modifierSizeMetres, modifierRectangleMetres, contactHardeningRatio,
  type FixturePhotometrics,
} from './photometry';

/**
 * The numbers, written down once for both languages.
 *
 * A native edition has to agree with this one about what a fixture puts out,
 * or the same scene document describes two different photographs. Rewriting the
 * arithmetic in Swift and then writing fresh Swift tests for it would only
 * assert that Swift agrees with itself.
 *
 * So this test computes every case from the TypeScript implementation and
 * asserts it against a committed JSON file that the Swift suite reads as well.
 * Change the arithmetic on either side and one of the two suites fails.
 *
 *   UPDATE_FIXTURES=1 npm test -- photometry.fixtures    # after a deliberate change
 *
 * Regenerating is a decision, not a build step: the file is in git, and a diff
 * on it is the record of a photographic change.
 */

const FIXTURE = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../../../apple/VirtualstudioCore/Tests/PhotometryTests/Fixtures/photometry.json',
);

/** Catalogue fixtures, at the figures their manufacturers publish. */
const SPECS: { name: string; spec: FixturePhotometrics }[] = [
  { name: 'Aputure LS 300d II', spec: { lux1m: 45000, beamAngleDeg: 55, type: 'led' } },
  { name: 'LED panel by lumens', spec: { lumens: 12000, beamAngleDeg: 90, type: 'led' } },
  { name: 'lumens with no beam published', spec: { lumens: 12000, type: 'led' } },
  { name: 'studio strobe', spec: { guideNumber: 87, lux1m: 3200, type: 'strobe' } },
  { name: 'speedlight', spec: { guideNumber: 58, type: 'speedlight' } },
  { name: 'practical bulb', spec: { lumens: 800, beamAngleDeg: 360, type: 'practical' } },
  { name: 'nothing usable', spec: { type: 'led' } },
  { name: 'zero output', spec: { lux1m: 0, lumens: 0, type: 'led' } },
];

const MODIFIERS: { label: string; glbFile?: string }[] = [
  { label: 'Softboks 90×120 cm' },
  { label: 'Stripbox 30×120 cm' },
  { label: 'Oktaboks 120 cm' },
  { label: 'Beautydish 42 cm' },
  { label: 'Diffusjonsramme 4×4 ft' },
  { label: 'Fresnel 12"' },
  { label: 'Softboks 90,5×120,5 cm' },
  { label: 'Snute', glbFile: 'snoot-stand.glb' },
  { label: 'Paraply', glbFile: '/models/lights/umbrella-stand.glb' },
  { label: 'Ukjent', glbFile: 'not-in-the-table.glb' },
  { label: 'Ingen mål' },
];

function build() {
  return {
    source: 'src/core/rendering/photometry.ts',
    note: 'Generated by photometry.fixtures.test.ts. Read by PhotometryTests in apple/VirtualstudioCore.',
    constants: {
      INCIDENT_METER_CONSTANT_C,
      SCENE_INTENSITY_PER_CANDELA,
      DEFAULT_BEAM_ANGLE_DEG,
      REFERENCE_SHUTTER_SECONDS,
      MAX_SPOT_CONE_RAD,
    },
    isFlashFixture: ['strobe', 'flash', 'speedlight', 'led', 'practical', 'hmi']
      .map(type => ({ type, flash: isFlashFixture(type) })),
    spotConeRadians: [10, 45, 55, 90, 120, 180, 360]
      .map(beamAngleDeg => ({ beamAngleDeg, radians: spotConeRadians(beamAngleDeg) })),
    coneSolidAngle: [10, 45, 55, 90, 120, 180, 360]
      .map(beamAngleDeg => ({ beamAngleDeg, steradian: coneSolidAngle(beamAngleDeg) })),
    fixtureCandela: SPECS.map(({ name, spec }) => ({ name, spec, candela: fixtureCandela(spec) })),
    illuminanceAt: [
      { candela: 45000, metres: 1 }, { candela: 45000, metres: 2 }, { candela: 45000, metres: 3 },
      { candela: 12000, metres: 1.5 }, { candela: 0, metres: 2 },
      // Below the minimum distance the reading holds rather than going to infinity.
      { candela: 45000, metres: 0.01 },
    ].map(({ candela, metres }) => ({ candela, metres, lux: illuminanceAt(candela, metres) })),
    distanceForIlluminance: [
      { candela: 45000, lux: 5000 }, { candela: 45000, lux: 45000 }, { candela: 1800, lux: 200 },
    ].map(({ candela, lux }) => ({ candela, lux, metres: distanceForIlluminance(candela, lux) })),
    stopsBetween: [
      { from: 1000, to: 2000 }, { from: 2000, to: 1000 }, { from: 5000, to: 5000 },
      { from: 1250, to: 5000 },
    ].map(({ from, to }) => ({ from, to, stops: stopsBetween(from, to) })),
    evAtIso100: [2.5, 250, 2500, 5000, 45000]
      .map(lux => ({ lux, ev: evAtIso100(lux) })),
    apertureForIlluminance: [
      { lux: 5000, iso: 100, shutterSeconds: 1 / 125 },
      { lux: 2500, iso: 100, shutterSeconds: 1 / 125 },
      { lux: 5000, iso: 400, shutterSeconds: 1 / 125 },
      { lux: 5000, iso: 100, shutterSeconds: 1 / 60 },
    ].map(c => ({ ...c, aperture: apertureForIlluminance(c.lux, c.iso, c.shutterSeconds) })),
    flashLuminousExposureAt1m: [32, 58, 87]
      .map(guideNumber => ({ guideNumber, luxSeconds: flashLuminousExposureAt1m(guideNumber) })),
    flashEquivalentCandela: [
      { guideNumber: 58, shutterSeconds: REFERENCE_SHUTTER_SECONDS },
      { guideNumber: 87, shutterSeconds: REFERENCE_SHUTTER_SECONDS },
      { guideNumber: 87, shutterSeconds: 1 / 250 },
    ].map(c => ({ ...c, candela: flashEquivalentCandela(c.guideNumber, c.shutterSeconds) })),
    flashShutterCompensation: [1 / 60, 1 / 125, 1 / 250, 1 / 1000]
      .map(shutterSeconds => ({ shutterSeconds, factor: flashShutterCompensation(shutterSeconds) })),
    flashApertureAt: [
      { guideNumber: 87, metres: 3, iso: 100 },
      { guideNumber: 87, metres: 3, iso: 400 },
      { guideNumber: 58, metres: 2, iso: 100 },
    ].map(c => ({ ...c, aperture: flashApertureAt(c.guideNumber, c.metres, c.iso) })),
    sceneIntensityFromCandela: [0, 4500, 12000, 45000, 900000]
      .map(candela => ({ candela, intensity: sceneIntensityFromCandela(candela) })),
    modifierSizeMetres: MODIFIERS
      .map(({ label, glbFile }) => ({ label, glbFile: glbFile ?? null, metres: modifierSizeMetres(label, glbFile) })),
    modifierRectangleMetres: MODIFIERS
      .map(({ label, glbFile }) => ({ label, glbFile: glbFile ?? null, ...modifierRectangleMetres(label, glbFile) })),
    contactHardeningRatio: [
      // The comparison the product is built on: same distance, two modifiers.
      { sourceSizeMetres: modifierSizeMetres('Softboks 90×120 cm'), beamAngleRad: spotConeRadians(55) },
      { sourceSizeMetres: modifierSizeMetres('Stripbox 30×120 cm'), beamAngleRad: spotConeRadians(55) },
      { sourceSizeMetres: modifierSizeMetres('Oktaboks 120 cm'), beamAngleRad: spotConeRadians(55) },
      { sourceSizeMetres: 0.1, beamAngleRad: spotConeRadians(20) },
      // Both clamps.
      { sourceSizeMetres: 0.01, beamAngleRad: spotConeRadians(120) },
      { sourceSizeMetres: 4, beamAngleRad: spotConeRadians(20) },
    ].map(c => ({ ...c, ratio: contactHardeningRatio(c.sourceSizeMetres, c.beamAngleRad) })),
  };
}

describe('the numbers both editions have to agree on', () => {
  it('matches the fixture the Swift suite reads', () => {
    const current = build();
    if (process.env.UPDATE_FIXTURES) {
      mkdirSync(dirname(FIXTURE), { recursive: true });
      writeFileSync(FIXTURE, `${JSON.stringify(current, null, 2)}\n`);
    }
    // Through JSON both ways: the fixture is a file, and -0 does not survive
    // being written to one.
    expect(JSON.parse(JSON.stringify(current))).toEqual(JSON.parse(readFileSync(FIXTURE, 'utf8')));
  });

  it('states a stripbox is crisper than a softbox, which is the whole claim', () => {
    // Not a golden value: the ordering is the photographic fact, and it must
    // hold whatever the numbers become.
    const strip = contactHardeningRatio(modifierSizeMetres('Stripbox 30×120 cm'), spotConeRadians(55));
    const soft = contactHardeningRatio(modifierSizeMetres('Softboks 90×120 cm'), spotConeRadians(55));
    expect(strip).toBeLessThan(soft);
  });
});
