import { describe, it, expect } from 'vitest';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  EDITABLE_JOINTS, LIMB_CHAINS, DEG, DEFAULT_BONE_AXIS,
  clampJointQuaternion, isWithinLimits, freeAxes,
  quatFromEuler, eulerFromQuat, quatFromAxisAngle, multiplyQuat, conjugateQuat,
  swingTwist, quatAngle, limitQuatAngle, twistAngle, unitVector,
  type Quat, type Vec3,
} from './poseRig';

/**
 * The joint table and its limits, written down for both languages.
 *
 * This is the anatomical correctness of the product: seventeen joints, their
 * axes, and how far each may go. It is also the part most likely to be quietly
 * re-derived rather than ported, because quaternion code looks the same whatever
 * it computes. So every limit, every clamp result and every helper is generated
 * from the TypeScript and asserted in Swift against the same numbers.
 *
 *   UPDATE_FIXTURES=1 npm test -- poseRig.fixtures
 */

const FIXTURE = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../../../apple/VirtualstudioCore/Tests/PoseRigTests/Fixtures/poseRig.json',
);

const v = (x: number, y: number, z: number): Vec3 => ({ x, y, z });
const deg = (d: number) => d * DEG;

/** Bone axes worth testing: the default, an arm's own length, a diagonal. */
const AXES: { name: string; axis: Vec3 }[] = [
  { name: 'default (local Y)', axis: DEFAULT_BONE_AXIS },
  { name: 'along X, as an arm', axis: v(1, 0, 0) },
  { name: 'diagonal', axis: v(0.3, 0.8, -0.5) },
  { name: 'degenerate, falls back', axis: v(0, 0, 0) },
];

/** Rotations to push at every joint: inside, at the edge, and far outside. */
const ROTATIONS: { name: string; q: Quat }[] = [
  { name: 'rest', q: { x: 0, y: 0, z: 0, w: 1 } },
  { name: 'a small bend', q: quatFromEuler(v(deg(-20), 0, 0)) },
  { name: 'a folded elbow', q: quatFromEuler(v(deg(-90), 0, 0)) },
  { name: 'past a folded elbow', q: quatFromEuler(v(deg(-200), 0, 0)) },
  { name: 'the wrong way for an elbow', q: quatFromEuler(v(deg(40), 0, 0)) },
  { name: 'a reach forward', q: quatFromEuler(v(deg(-70), deg(30), deg(20))) },
  { name: 'a wrung neck', q: quatFromEuler(v(0, deg(120), 0)) },
  { name: 'sideways', q: quatFromEuler(v(0, 0, deg(100))) },
  { name: 'a half turn', q: quatFromAxisAngle(v(0, 1, 0), Math.PI) },
  { name: 'unnormalised', q: { x: 0.2, y: 0.4, z: 0.1, w: 1.7 } },
  { name: 'not a number at all', q: { x: Number.NaN, y: 0, z: 0, w: 1 } },
  { name: 'all zero', q: { x: 0, y: 0, z: 0, w: 0 } },
];

function build() {
  return {
    source: 'src/core/rendering/poseRig.ts',
    note: 'Generated by poseRig.fixtures.test.ts. Read by PoseRigTests in apple/VirtualstudioCore.',
    DEG,
    joints: EDITABLE_JOINTS.map(joint => ({
      id: joint.id, node: joint.node, label: joint.label,
      limits: joint.limits, freeAxes: freeAxes(joint),
    })),
    limbChains: LIMB_CHAINS,
    // `normalizeQuat` is internal to poseRig.ts, so it is not pinned directly;
    // every function below normalises its input, which is where it shows.
    unitVector: AXES.map(({ name, axis }) => ({ name, axis, unit: unitVector(axis) })),
    quatAngle: ROTATIONS.map(({ name, q }) => ({ name, q, radians: quatAngle(q) })),
    // The product of two rotations, in the order the renderer multiplies them.
    multiplyQuat: [
      { a: quatFromEuler(v(deg(30), 0, 0)), b: quatFromEuler(v(0, deg(45), 0)) },
      { a: quatFromAxisAngle(v(0, 0, 1), deg(90)), b: quatFromAxisAngle(v(1, 0, 0), deg(90)) },
    ].map(({ a, b }) => ({ a, b, product: multiplyQuat(a, b), conjugateOfA: conjugateQuat(a) })),
    swingTwist: AXES.flatMap(({ name: axisName, axis }) =>
      ROTATIONS.map(({ name, q }) => {
        const split = swingTwist(q, axis);
        return { rotation: name, axis: axisName, axisVector: axis, q, ...split };
      })),
    limitQuatAngle: ROTATIONS.flatMap(({ name, q }) =>
      [deg(20), deg(90), deg(150)].map(maxAngle => ({ name, q, maxAngle, limited: limitQuatAngle(q, maxAngle) }))),
    twistAngle: AXES.flatMap(({ name: axisName, axis }) =>
      ROTATIONS.map(({ name, q }) => ({ rotation: name, axis: axisName, axisVector: axis, q, radians: twistAngle(q, axis) }))),
    // The whole point: every joint, every rotation, every axis.
    clamped: EDITABLE_JOINTS.flatMap(joint =>
      AXES.flatMap(({ name: axisName, axis }) =>
        ROTATIONS.map(({ name, q }) => ({
          joint: joint.id, rotation: name, axis: axisName, axisVector: axis, q,
          clamped: clampJointQuaternion(joint.id, q, axis),
          within: isWithinLimits(joint.id, q, axis),
        })))),
    euler: [
      v(0, 0, 0), v(deg(30), 0, 0), v(0, deg(30), 0), v(0, 0, deg(30)),
      v(deg(-90), deg(20), deg(15)), v(deg(45), deg(89), deg(-30)),
    ].map(angles => {
      const q = quatFromEuler(angles);
      return { angles, q, back: eulerFromQuat(q) };
    }),
  };
}

describe('the joint table and its limits, for both editions', () => {
  it('matches the fixture the Swift suite reads', () => {
    const current = build();
    if (process.env.UPDATE_FIXTURES) {
      mkdirSync(dirname(FIXTURE), { recursive: true });
      writeFileSync(FIXTURE, `${JSON.stringify(current, null, 2)}\n`);
    }
    // Through JSON both ways: the fixture is a file, and -0 does not survive
    // being written to one.
    expect(JSON.parse(JSON.stringify(current))).toEqual(JSON.parse(readFileSync(FIXTURE, 'utf8')));
  });

  it('pushes every joint outside its range somewhere, or it would prove nothing', () => {
    // A fixture where every rotation happened to be legal would assert only
    // that the clamp returns its input.
    const refused = build().clamped.filter(entry => !entry.within);
    expect(refused.length).toBeGreaterThan(100);
    for (const joint of EDITABLE_JOINTS) {
      expect(refused.some(entry => entry.joint === joint.id), joint.id).toBe(true);
    }
  });
});
