/**
 * Video Chapter Manager
 * Automatic chapter detection and manual chapter markers for video content
 */

import { useTheming } from '../../utils/theming-helper';
import { useEnhancedMasterIntegration } from '@/integration/EnhancedMasterIntegrationProvider';
import { withUniversalIntegration } from '@/integration/UniversalIntegrationHOC';
import { useAcademy } from '@/contexts/AcademyContext';
import React, { useState, useRef, useCallback, useEffect } from 'react';
import {
  Box,
  Paper,
  Typography,
  Button,
  TextField,
  IconButton,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  List,
  ListItem,
  ListItemText,
  ListItemSecondaryAction,
  Chip,
  Stack,
  Slider,
  Switch,
  FormControlLabel,
  Divider,
  Alert,
  LinearProgress,
  Tooltip,
  useTheme,
  alpha,
} from '@mui/material';
import {
  Add,
  Edit,
  Delete,
  PlayArrow,
  Pause,
  AutoAwesome,
  Bookmark,
  ContentCopy,
  Visibility,
  VisibilityOff,
  DragIndicator,
  CheckCircle,
  Warning,
  Info,
  Close,
  Refresh,
} from '@mui/icons-material';
import {
  BookmarkIcon,
  NoteIcon,
  XRayIcon,
  SpeedIcon,
  ChapterIcon,
  ThumbnailIcon,
  AutoDetectIcon,
  VideoProcessingIcon,
  VideoMarkerIcon,
  ContentCreationIcon,
} from '../shared/CreatorHubIcons';

export interface VideoChapter {
  id: string;
  title: string;
  description?: string;
  startTime: number;
  endTime?: number;
  duration?: number;
  thumbnail?: string;
  isAutoGenerated: boolean;
  confidence?: number; // For auto-generated chapters
  tags?: string[];
  isVisible: boolean;
  createdAt: string;
  updatedAt: string;
}

interface VideoChapterManagerProps {
	  videoUrl: string;
	  duration: number;
	  chapters: VideoChapter[];
	  onChaptersChange: (chapters: VideoChapter[]) => void;
	  onSave?: (chapters: VideoChapter[]) => void;
	  onCancel?: () => void;
	  onAutoDetect?: (videoUrl: string) => Promise<VideoChapter[]>;
}

function VideoChapterManager({
  videoUrl,
  duration,
  chapters,
  onChaptersChange,
  onSave,
  onCancel,
  onAutoDetect,
}: VideoChapterManagerProps) {
  const theme = useTheme();

  // Theming system
  const theming = useTheming('music_producer');

  // Enhanced Master Integration
  const { analytics, performance, debugging, lifecycle, health, features } =
    useEnhancedMasterIntegration();

  // Academy Context
  const { updateProgress, addBookmark, addNote, updateSettings, state } = useAcademy();

  const videoRef = useRef<HTMLVideoElement>(null);
  const [currentTime, setCurrentTime] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [selectedChapter, setSelectedChapter] = useState<VideoChapter | null>(null);
  const [showChapterDialog, setShowChapterDialog] = useState(false);
  const [editingChapter, setEditingChapter] = useState<VideoChapter | null>(null);
  const [isAutoDetecting, setIsAutoDetecting] = useState(false);
  const [autoDetectProgress, setAutoDetectProgress] = useState(0);
  const [showPreview, setShowPreview] = useState(false);

  // Component registration and analytics
  useEffect(() => {
    const endTiming = performance.startTiming('video_chapter_manager_render');

    analytics.trackEvent('video_chapter_manager_mounted,', {
      videoUrl,
      duration,
      chapterCount: chapters.length,
      timestamp: Date.now(),
    });

    debugging.logIntegration('info', 'VideoChapterManager mounted', {
      videoUrl,
      duration,
      chapterCount: chapters.length,
    });

    return () => {
      endTiming();
      analytics.trackEvent('video_chapter_manager_unmounted', {
        videoUrl,
        duration,
        chapterCount: chapters.length,
        timestamp: Date.now(),
      });
    };
  }, [videoUrl, duration, chapters.length, analytics, performance, debugging]);

  // Video event handlers
  const handlePlay = useCallback(() => {
    if (videoRef.current) {
      videoRef.current.play();
      setIsPlaying(true);
    }
  }, []);

  const handlePause = useCallback(() => {
    if (videoRef.current) {
      videoRef.current.pause();
      setIsPlaying(false);
    }
  }, []);

  const handleSeek = useCallback(
    (event: Event, newValue: number | number[], activeThumb?: number) => {
      if (videoRef.current) {
        const newTime = newValue as number;
        videoRef.current.currentTime = newTime;
        setCurrentTime(newTime);
      }
    },
    [],
  );

  const handleTimeUpdate = useCallback(() => {
    if (videoRef.current) {
      setCurrentTime(videoRef.current.currentTime);
    }
  }, []);

  // Chapter management
  const handleAddChapter = useCallback(() => {
    const newChapter: VideoChapter = {
      id: `chapter-${Date.now()}`,
      title: `Chapter ${chapters.length + 1}`,
      startTime: currentTime,
      isAutoGenerated: false,
      isVisible: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    setEditingChapter(newChapter);
    setShowChapterDialog(true);

    // Analytics tracking
    analytics.trackEvent('chapter_added', {
      chapterId: newChapter.id,
      startTime: currentTime,
      videoUrl,
      duration,
      chapterCount: chapters.length + 1,
      timestamp: Date.now(),
    });
  }, [currentTime, chapters.length, analytics, videoUrl, duration]);

  const handleEditChapter = useCallback((chapter: VideoChapter) => {
    setEditingChapter(chapter);
    setShowChapterDialog(true);
  }, []);

  const handleSaveChapter = useCallback(
    (chapter: VideoChapter) => {
      const updatedChapters = editingChapter
        ? chapters.map((c) => (c.id === editingChapter.id ? chapter : c))
        : [...chapters, chapter];

      // Sort chapters by start time
      updatedChapters.sort((a, b) => a.startTime - b.startTime);

      onChaptersChange(updatedChapters);
      setShowChapterDialog(false);
      setEditingChapter(null);

      // Analytics tracking
      analytics.trackEvent('chapter_saved', {
        chapterId: chapter.id,
        title: chapter.title,
        startTime: chapter.startTime,
        isAutoGenerated: chapter.isAutoGenerated,
        videoUrl,
        duration,
        totalChapters: updatedChapters.length,
        timestamp: Date.now(),
      });
    },
    [chapters, editingChapter, onChaptersChange, analytics, videoUrl, duration],
  );

  const handleDeleteChapter = useCallback(
    (chapterId: string) => {
      const updatedChapters = chapters.filter((c) => c.id !== chapterId);
      onChaptersChange(updatedChapters);

      // Analytics tracking
      analytics.trackEvent('chapter_deleted', {
        chapterId,
        videoUrl,
        duration,
        remainingChapters: updatedChapters.length,
        timestamp: Date.now(),
      });
    },
    [chapters, onChaptersChange, analytics, videoUrl, duration],
  );

  const handleChapterClick = useCallback((chapter: VideoChapter) => {
    if (videoRef.current) {
      videoRef.current.currentTime = chapter.startTime;
      setCurrentTime(chapter.startTime);
    }
  }, []);

  // Auto-detect chapters
  const handleAutoDetect = useCallback(async () => {
    if (!onAutoDetect) return;

    setIsAutoDetecting(true);
    setAutoDetectProgress(0);

    try {
      // Simulate progress
      const progressInterval = setInterval(() => {
        setAutoDetectProgress((prev) => {
          if (prev >= 90) {
            clearInterval(progressInterval);
            return prev;
          }
          return prev + 10;
        });
      }, 200);

      const detectedChapters = await onAutoDetect(videoUrl);

      clearInterval(progressInterval);
      setAutoDetectProgress(100);

      // Merge with existing chapters (avoid duplicates)
      const existingTimes = chapters.map((c) => c.startTime);
      const newChapters = detectedChapters.filter(
        (c) => !existingTimes.some((time) => Math.abs(time - c.startTime) < 5),
      );

      onChaptersChange([...chapters, ...newChapters]);

      setTimeout(() => {
        setIsAutoDetecting(false);
        setAutoDetectProgress(0);
      }, 1000);
    } catch (error) {
      console.error('Auto-detection failed: ', error);
      setIsAutoDetecting(false);
      setAutoDetectProgress(0);
    }
  }, [onAutoDetect, videoUrl, chapters, onChaptersChange]);

  // Generate thumbnails for chapters
  const generateThumbnail = useCallback(async (time: number): Promise<string> => {
    if (!videoRef.current) return ', ';

    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (!ctx) return ', ';

    // Set canvas size
    canvas.width = 320;
    canvas.height = 180;

    // Seek to time and capture frame
    const video = videoRef.current;
    const originalTime = video.currentTime;
    video.currentTime = time;

    await new Promise((resolve) => {
      video.addEventListener('seeked', resolve, { once: true });
    });

    // Draw video frame to canvas
    ctx.drawImage(video, 0, 0, canvas.width, canvas.height);

    // Restore original time
    video.currentTime = originalTime;

    return canvas.toDataURL('image/jpeg', 0.8);
  }, []);

  // Calculate chapter durations
  useEffect(() => {
    const updatedChapters = chapters.map((chapter, index) => {
      const nextChapter = chapters[index + 1];
      const endTime = nextChapter ? nextChapter.startTime : duration;
      return {
        ...chapter,
        endTime,
        duration: endTime - chapter.startTime,
      };
    });

    if (JSON.stringify(updatedChapters) !== JSON.stringify(chapters)) {
      onChaptersChange(updatedChapters);
    }
  }, [chapters, duration, onChaptersChange]);

  return (
    <Box sx={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
      {/* Header */}
      <Box sx={{ p: 2, borderBottom: 1, borderColor: 'divider' }}>
        <Stack direction="row" spacing={2} alignItems="center" justifyContent="space-between">
          <Typography variant="h6" sx={{ color: theming.colors.primary }}>
            Video Chapter Manager
          </Typography>
          <Stack direction="row" spacing={1}>
            <FormControlLabel
              control={
                <Switch checked={showPreview} onChange={(e) => setShowPreview(e.target.checked)} />
              }
              label="Preview"
            />
            <Button variant="outlined" onClick={onCancel}>
              Cancel
            </Button>
            <Button
              variant="contained"
              onClick={() => onSave?.(chapters)}
              sx={theming.getThemedButtonSx()}
            >
              Save Chapters
            </Button>
          </Stack>
        </Stack>
      </Box>

      {/* Auto-detect Progress */}
      {isAutoDetecting && (
        <Box sx={{ p: 2 }}>
          <Alert severity="info" sx={{ mb: 2 }}>
            <Stack direction="row" alignItems="center" spacing={2}>
              <AutoAwesome />
              <Typography>Auto-detecting chapters...</Typography>
            </Stack>
          </Alert>
          <LinearProgress variant="determinate" value={autoDetectProgress} />
        </Box>
      )}

      {/* Main Content */}
      <Box sx={{ flex: 1, display: 'flex' }}>
        {/* Video Player */}
        <Box sx={{ flex: 1, position: 'relative' }}>
          <video
            ref={videoRef}
            src={videoUrl}
            onTimeUpdate={handleTimeUpdate}
            style={{
              width: '100%',
              height: '100%',
              objectFit: 'contain'}}
          />

          {/* Chapter Markers Overlay */}
          {showPreview && (
            <Box
              sx={{
                position: 'absolute',
                top: 0,
                left: 0,
                right: 0,
                bottom: 0,
                pointerEvents: 'none'}}
            >
              {chapters.map((chapter) => (
                <Box
                  key={chapter.id}
                  sx={{
                    position: 'absolute',
                    left: `${(chapter.startTime / duration) * 100}%`,
                    top: 0,
                    bottom: 0,
                    width: 2,
                    bgcolor: chapter.isAutoGenerated ? '#2196f3' : '#ff8c00',
                    zIndex: 1}}
                />
              ))}
            </Box>
          )}

          {/* Video Controls */}
          <Box
            sx={{
              position: 'absolute',
              bottom: 0,
              left: 0,
              right: 0,
              background: 'linear-gradient(to top, rgba(0,0,0,0.8), transparent)',
              p: 2,
              zIndex: 2}}
          >
            <Stack direction="row" alignItems="center" spacing={2}>
              <IconButton onClick={isPlaying ? handlePause : handlePlay} sx={{ color: 'white' }}>
                {isPlaying ? <Pause /> : <PlayArrow />}
              </IconButton>

              <Typography variant="body2" sx={{ color: 'white', minWidth: 100 }}>
                {Math.floor(currentTime / 60)}:{(currentTime % 60).toFixed(0).padStart(2, '0')} /{', '}
                {Math.floor(duration / 60)}:{(duration % 60).toFixed(0).padStart(2, '0')}
              </Typography>

              <Box sx={{ flex: 1 }}>
                <Slider
                  value={currentTime}
                  min={0}
                  max={duration}
                  onChange={handleSeek}
                  sx={{
                    color: '#ff8c00','& .MuiSlider-thumb': {
                      width: 16,
                      height: 16,
                      bgcolor: '#ff8c00',
                    }}}
                />
              </Box>
            </Stack>
          </Box>
        </Box>

        {/* Chapter Tools */}
        <Box sx={{ width: 400, borderLeft: 1, borderColor: 'divider', p: 2 }}>
          <Stack spacing={2}>
            <Typography variant="h6" sx={{ color: theming.colors.primary }}>
              Chapter Management
            </Typography>

            {/* Action Buttons */}
            <Stack direction="row" spacing={1}>
              <Button
                variant="contained"
                startIcon={<Add />}
                onClick={handleAddChapter}
                fullWidth
                sx={theming.getThemedButtonSx()}
              >
                Add Chapter
              </Button>
              {onAutoDetect && (
                <Button
                  variant="outlined"
                  startIcon={<AutoAwesome />}
                  onClick={handleAutoDetect}
                  disabled={isAutoDetecting}
                  fullWidth
                >
                  Auto-Detect
                </Button>
              )}
            </Stack>

            <Divider />

            {/* Chapters List */}
            <Box>
              <Typography variant="subtitle2" gutterBottom>
                Chapters ({chapters.length})
              </Typography>
              <List dense>
                {chapters.map((chapter, index) => (
                  <ListItem
                    key={chapter.id}
                    component="button"
                    onClick={() => handleChapterClick(chapter)}
                    sx={{
                      borderRadius: 1,
                      mb: 1,
                      bgcolor:
                        selectedChapter?.id === chapter.id
                          ? alpha(theme.palette.primary.main, 0.1)
                          : 'transparent'}}
                  >
                    <ListItemText
                      primary={
                        <Stack direction="row" alignItems="center" spacing={1}>
                          <Typography variant="body2" fontWeight="medium">
                            {chapter.title}
                          </Typography>
                          {chapter.isAutoGenerated && (
                            <Chip
                              label="Auto"
                              size="small"
                              color="primary"
                              icon={<AutoAwesome />}
                            />
                          )}
                          {chapter.confidence && (
                            <Chip
                              label={`${Math.round(chapter.confidence * 100)}%`}
                              size="small"
                              color={chapter.confidence > 0.8 ? 'success' : 'warning'}
                            />
                          )}
                        </Stack>
                      }
                      secondary={
                        <Stack spacing={0.5}>
                          <Typography variant="caption" color="text.secondary">
                            {Math.floor(chapter.startTime / 60)}:
                            {(chapter.startTime % 60).toFixed(0).padStart(2, '0')}
                            {chapter.endTime &&
                              ` - ${Math.floor(chapter.endTime / 60)}:${(chapter.endTime % 60).toFixed(0).padStart(2, '0')}`}
                            {chapter.duration &&
                              ` (${Math.floor(chapter.duration / 60)}:${(chapter.duration % 60).toFixed(0).padStart(2, '0')})`}
                          </Typography>
                          {chapter.description && (
                            <Typography variant="caption" color="text.secondary">
                              {chapter.description}
                            </Typography>
                          )}
                          {chapter.tags && chapter.tags.length > 0 && (
                            <Stack direction="row" spacing={0.5} flexWrap="wrap">
                              {chapter.tags.map((tag, tagIndex) => (
                                <Chip key={tagIndex} label={tag} size="small" variant="outlined" />
                              ))}
                            </Stack>
                          )}
                        </Stack>
                      }
                    />
                    <ListItemSecondaryAction>
                      <Stack direction="row" spacing={0.5}>
                        <IconButton
                          size="small"
                          onClick={(e) => {
                            e.stopPropagation();
                            handleEditChapter(chapter);
                          }}
                        >
                          <Edit />
                        </IconButton>
                        <IconButton
                          size="small"
                          onClick={(e) => {
                            e.stopPropagation();
                            handleDeleteChapter(chapter.id);
                          }}
                        >
                          <Delete />
                        </IconButton>
                      </Stack>
                    </ListItemSecondaryAction>
                  </ListItem>
                ))}
              </List>
            </Box>
          </Stack>
        </Box>
      </Box>

      {/* Chapter Dialog */}
      <Dialog
        open={showChapterDialog}
        onClose={() => setShowChapterDialog(false)}
        maxWidth="md"
        fullWidth
      >
        <DialogTitle>{editingChapter ? 'Edit Chapter' : 'Add Chapter'}</DialogTitle>
        <DialogContent>
          {editingChapter && (
            <ChapterForm
              chapter={editingChapter}
              onSave={handleSaveChapter}
              onCancel={() => setShowChapterDialog(false)}
              onGenerateThumbnail={generateThumbnail}
            />
          )}
        </DialogContent>
      </Dialog>
    </Box>
  );
}

// Chapter Form Component
interface ChapterFormProps {
  chapter: VideoChapter;
  onSave: (chapter: VideoChapter) => void;
  onCancel: () => void;
  onGenerateThumbnail: (time: number) => Promise<string>;
}

function ChapterForm({ chapter, onSave, onCancel, onGenerateThumbnail }: ChapterFormProps) {
  const [formData, setFormData] = useState<VideoChapter>(chapter);
  const [isGeneratingThumbnail, setIsGeneratingThumbnail] = useState(false);

  const handleSave = () => {
    onSave({
      ...formData,
      updatedAt: new Date().toISOString(),
    });
  };

  const handleGenerateThumbnail = async () => {
    setIsGeneratingThumbnail(true);
    try {
      const thumbnail = await onGenerateThumbnail(formData.startTime);
      setFormData((prev) => ({ ...prev, thumbnail }));
    } catch (error) {
      console.error('Failed to generate thumbnail:', error);
    } finally {
      setIsGeneratingThumbnail(false);
    }
  };

  return (
    <Stack spacing={3} sx={{ mt: 1 }}>
      <TextField
        label="Chapter Title"
        value={formData.title}
        onChange={(e) => setFormData((prev) => ({ ...prev, title: e.target.value }))}
        fullWidth
        required
      />

      <TextField
        label="Description"
        value={formData.description || ', '}
        onChange={(e) => setFormData((prev) => ({ ...prev, description: e.target.value }))}
        multiline
        rows={2}
        fullWidth
      />

      <Stack direction="row" spacing={2}>
        <TextField
          label="Start Time (seconds)"
          type="number"
          value={formData.startTime}
          onChange={(e) => setFormData((prev) => ({ ...prev, startTime: Number(e.target.value) }))}
          fullWidth
          required
        />
        <TextField
          label="End Time (seconds)"
          type="number"
          value={formData.endTime || ', '}
          onChange={(e) => setFormData((prev) => ({ ...prev, endTime: Number(e.target.value) }))}
          fullWidth
        />
      </Stack>

      <TextField
        label="Tags (comma-separated)"
        value={formData.tags?.join(', ') || ''}
        onChange={(e) =>
          setFormData((prev) => ({
            ...prev,
            tags: e.target.value
              .split(', ')
              .map((tag) => tag.trim())
              .filter(Boolean),
          }))
        }
        fullWidth
        placeholder="e.g., introduction, tutorial, advanced"
      />

      <FormControlLabel
        control={
          <Switch
            checked={formData.isVisible}
            onChange={(e) => setFormData((prev) => ({ ...prev, isVisible: e.target.checked }))}
          />
        }
        label="Visible in player"
      />

      {/* Thumbnail Section */}
      <Box>
        <Typography variant="subtitle2" gutterBottom>
          Chapter Thumbnail
        </Typography>
        <Stack direction="row" spacing={2} alignItems="center">
          {formData.thumbnail && (
            <Box
              component="img"
              src={formData.thumbnail}
              alt="Chapter thumbnail"
              sx={{
                width: 120,
                height: 68,
                objectFit: 'cover',
                borderRadius: 1,
                border: 1,
                borderColor: 'divider'}}
            />
          )}
          <Button
            variant="outlined"
            onClick={handleGenerateThumbnail}
            disabled={isGeneratingThumbnail}
            startIcon={<AutoAwesome />}
          >
            {isGeneratingThumbnail ? 'Generating...' : 'Generate Thumbnail'}
          </Button>
        </Stack>
      </Box>

      <DialogActions>
        <Button onClick={onCancel}>Cancel</Button>
        <Button variant="contained" onClick={handleSave}>
          Save Chapter
        </Button>
      </DialogActions>
    </Stack>
  );
}

export default withUniversalIntegration(VideoChapterManager, {
  componentId: 'video-chapter-manager',
  componentName: 'Video Chapter Manager',
  componentType: 'editor',
  componentCategory:'academy',
	  featureIds: ['chapter-manager', 'video-processing'],
});
